//
// menu_credits.c
//
// Copyright 1998 Raven Software
//

#include "client.h"
#include "qcommon.h"
#include "menu_credits.h"

#pragma region ========================== THE CREDITS ==========================

static char* raven_credits[] =
{
	"+HERETIC II",
	"",
	"+BY RAVEN SOFTWARE",
	"+A STUDIO OF ACTIVISION, INC.",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"+---------------",
	"+HERETIC II TEAM",
	"+---------------",
	"",
	"",
	"",
	"",
	"+CREATIVE DIRECTORS",
	"",
	"Brian Raffel",
	"Steve Raffel",
	"",
	"",
	"+PROJECT LEADER AND ART DIRECTOR",
	"",
	"Brian Pelletier",
	"",
	"",
	"+PRODUCER",
	"",
	"Steve Stringer",
	"",
	"",
	"+LEAD PROGRAMMER",
	"",
	"Patrick Lipo",
	"",
	"",
	"+ASSISTANT LEAD PROGRAMMER",
	"",
	"Jake Simpson",
	"",
	"",
	"+LEAD DESIGNER",
	"",
	"Jon Zuk",
	"",
	"",
	"+LEAD 2D ARTIST",
	"",
	"Jeff Butler",
	"",
	"",
	"+LEAD SOUND DESIGN",
	"",
	"Kevin Schilder",
	"",
	"",
	"+PROJECT ADMINISTRATOR",
	"",
	"Dan Freed",
	"",
	"",
	"",
	"",
	"+DESIGNERS",
	"",
	"Michael Ramond-Judy",
	"Matt Pinkston",
	"Mike Renner",
	"Tom Odell",
	"Jeremy Statz",
	"Tim Jervis",
	"Brian Raffel",
	"",
	"",
	"+ADDITIONAL DESIGN",
	"",
	"Chris Foster",
	"Eric Biessman",
	"Bobby Duncanson",
	"",
	"",
	"",
	"",
	"+PROGRAMMERS",
	"",
	"-Patrick Lipo-",
	"Player, Weapon and Game Programming",
	"",
	"-Bob Love-",
	"Game Programming and Art Asset Coordination",
	"",
	"-Marcus Whitlock-",
	"Camera, Network, and Game Programming",
	"",
	"-John Scott-",
	"Interface, Hardware, and Low-Level Programming",
	"",
	"-Josh Weier-",
	"Player, Monster and Game Programming",
	"",
	"-Mike Gummelt-",
	"Monster and Game Programming",
	"",
	"-Jake Simpson-",
	"Low-Level and Game Programming",
	"",
	"-Gil Gribb-",
	"Chief Technologist",
	"",
	"",
	"",
	"+ADDITIONAL PROGRAMMING",
	"",
	"-Rick Johnson-",
	"Scripting System and Quake Engine Expert",
	"",
	"-Josh Heitzman-",
	"Assistant Technologist",
	"",
	"-James Monroe-",
	"3rd Party Support and Programming",
	"",
	"-Nathan McKenzie-",
	"Additional Weapon Effect Programming",
	"",
	"-Steve Sengele-",
	"Additional AI and Special Effect Programming",
	"",
	"-Dan Kramer-",
	"Quake Editor Support and Modification",
	"",
	"",
	"",
	"",
	"+QUAKE II TECHNOLOGY",
	"",
	"John Carmack",
	"Id Software",
	"",
	"",
	"",
	"",
	"+ARTISTS",
	"",
	"-Jeff Butler-",
	"Concept Art, Level Textures, Object Skins,",
	"Corvus Skin, Creature Skins.",
	"",
	"-Rob Gee-",
	"Concept Art, Level textures, Interface Graphics,",
	"Object Skins, Creature Skins.",
	"",
	"-Jeffery P. Lampo-",
	"3D Objects, Object Animations.",
	"",
	"-Gina Garren-",
	"Level Textures, Object Skins, Creature Skins.",
	"",
	"-Kim Lathrop-",
	"Level Textures, Object Skins, Creature Skins.",
	"",
	"-Mark A. Nelson-",
	"Concept Art, Level Textures, Object Skins,",
	"Creature Skins.",
	"",
	"-Brian Pelletier-",
	"Concept Art, 3D Objects, Level Textures.",
	"",
	"-Les Dorscheid-",
	"Concept Art, 3D Objects.",
	"",
	"",
	"+ADDITIONAL ARTWORK",
	"",
	"-Joe Koberstein-",
	"Concept Art, Level Textures.",
	"",
	"-Kevin Long-",
	"Concept Art, Level Textures.",
	"",
	"-Steve Raffel-",
	"Level Textures, Raven Software Animated Logo",
	"",
	"-Brian Raffel-",
	"Sky Textures.",
	"",
	"-Scott Rice-",
	"Level Textures.",
	"",
	"",
	"",
	"",
	"+ANIMATORS",
	"",
	"-Brian Shubat-",
	"Corvus, Plague Elves. Cut scene animations.",
	"",
	"-Jeff Dewitt-",
	"Plague Spreader, Celestial Watcher, ",
	"Gorgon, Carthorian Assassin, Trial Beast,",
	"Morcalavin, Additional Corvus and ",
	"G'krokon animations. Cut scene animations,",
	"2D Concept art.",
	"",
	"-John Payne-",
	"Rat, Myxini, Mutant Ssithra, ",
	"High Priestess, Overlord, Guard, T'chekrik.",
	"Cut scene animations.",
	"",
	"-Eric Turman-",
	"Harpy, Plague Ssithra, T'chekrik",
	"",
	"",
	"+ADDITIONAL ANIMATIONS",
	"",
	"-Jarrod Showers-",
	"Chicken, Cut scene animations",
	"",
	"-Mike Werckle-",
	"G'krokon",
	"",
	"",
	"",
	"",
	"+CREATURE CONCEPTUALIZATION AND",
	"+BOX COVER PAINTING",
	"",
	"Brom",
	"",
	"",
	"",
	"",
	"+SOUND EFFECTS AND MUSIC",
	"",
	"Kevin Schilder",
	"",
	"",
	"+ADDITIONAL SOUND",
	"",
	"Chia Chin Lee",
	"",
	"",
	"",
	"+DIRECTOR OF PRODUCT DEVELOPMENT",
	"",
	"Mike Crowns",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"+------------------------",
	"+ACTIVISION - LOS ANGELES",
	"+------------------------",
	"",
	"",
	"",
	"",
	"+ASSOCIATE PRODUCER",
	"",
	"Steven Rosenthal",
	"",
	"",
	"",
	"",
	"+PRODUCTION TESTING",
	"",
	"Steven Rosenthal",
	"Steve Elwell",
	"Shane McAllen",
	"",
	"",
	"+ADDITIONAL PRODUCTION TESTING",
	"",
	"Chris Ovitz",
	"",
	"",
	"",
	"",
	"+QUALITY ASSURANCE",
	"",
	"",
	"+SENIOR QA LEAD",
	"",
	"Curtis Shenton",
	"",
	"",
	"+QA LEAD",
	"",
	"Dave Baker",
	"",
	"",
	"+QA TEAM",
	"",
	"Gene Bahng",
	"Paul Baker",
	"Thomas R. Bissell III",
	"Chad Bordwell",
	"Ben Deguzman",
	"Damien Fischer",
	"Aaron Gray",
	"Glenn Ige",
	"Derek Johnstone",
	"Eric Koch",
	"Eric Lee",
	"Justin Mills",
	"Talmadge Morning",
	"Edward Murphy",
	"Matt Powers",
	"Paul Sauser",
	"Brian Ullmer",
	"Jon Virtes",
	"Mohammed Wright",
	"Miguel, the Wonder Llama",
	"",
	"",
	"+VP OF CS/QA",
	"",
	"Jim Summers",
	"",
	"",
	"+QA MANAGER",
	"",
	"Dave Arnspiger",
	"",
	"",
	"",
	"",
	"+MARKETING TEAM",
	"",
	"+PRODUCT MANAGER",
	"",
	"Steve Felsen",
	"",
	"",
	"+ASSOCIATE PRODUCT MANAGER",
	"",
	"Kevin Kraff",
	"",
	"",
	"+PUBLICITY MANAGER",
	"",
	"Maryanne Latiaf",
	"",
	"",
	"+PR ASSOCIATE",
	"",
	"Caroline Poon",
	"",
	"",
	"",
	"",
	"+ONLINE PRODUCTION COORDINATOR",
	"",
	"William Mull",
	"",
	"",
	"+WEB SITE ARTIST",
	"",
	"Charles Hinshaw",
	"",
	"",
	"",
	"",
	"+LOCALIZATIONS",
	"",
	"",
	"+INTERNATIONAL PUBLISHING",
	"",
	"Sandi Isaacs",
	"Peter Oey",
	"Ed Bainbridge",
	"",
	"",
	"+CREATIVE SERVICES MANAGER-EUROPE",
	"",
	"Lucy Morgan",
	"",
	"",
	"+INTERNATIONAL PUBLISHING",
	"",
	"Ernie Maldonado",
	"Janine Johnson",
	"John Burns",
	"Patrick Chachuat",
	"Wolfram Von Eichborn",
	"John Watts",
	"Margaret Lawson",
	"",
	"",
	"+LOCALIZATION SUPERVISORS",
	"Jonathan Eubanks",
	"Nicky Kerth",
	"Natascha Conrad",
	"Salvador Fernandez",
	"",
	"",
	"+MARKETING PRODUCT MANAGERS",
	"",
	"Simon Jones",
	"Laurent Danet",
	"Andreas Stock",
	"Paul Butcher",
	"",
	"",
	"ARE YOU SERIOUSLY STILL READING ALL THIS ?",
	"",
	"",
	"",
	"+MANUAL and INSTALLER TEAMS",
	"",
	"+MANUAL WRITING",
	"Daniell Freed",
	"Christopher Foster",
	"",
	"",
	"+MANUAL LAYOUT",
	"",
	"Belinda M. Van Sickle",
	"",
	"",
	"+INSTALLER",
	"",
	"Steve Stringer",
	"",
	"",
	"+INSTALLER AND PRODUCTION TESTING INTERN",
	"",
	"Justin Barad",
	"",
	"",
	"",
	"",
	"+CINEMATICS AND VOICE-OVER",
	"",
	"",
	"+RENDERED CINEMATICS",
	"",
	"Creat Studio, San Francisco, USA & St. Petersburg, Russia",
	"",
	"",
	"+STORY BY",
	"Daniell Freed",
	"Brian Pelletier",
	"",
	"",
	"+SCRIPT BY",
	"",
	"Daniell Freed",
	"Brian Pelletier",
	"Scott Krager",
	"",
	"",
	"+VOICE DIRECTION",
	"",
	"Kris Zimmerman",
	"",
	"",
	"+VOICE-OVER TALENT",
	"+(in alphabetical order)",
	"",
	"-Rebecca Downs-",
	"The Tome of Power and the High Priestess",
	"",
	"-Kay Kuter-",
	"Siernan",
	"",
	"-Daniel Riordian-",
	"Corvus, the Celestial Watcher, and Morcalavin",
	"",
	"-Wally Wingert-",
	"D'Sparil, Dranor, Scout, Ssithra, and the Guardian",
	"",
	"-Miguel, the Wonder Llama-",
	"Himself",
	"",
	"Recorded at Screenmusic Studios",
	"in Studio City, California",
	"",
	"",
	"",
	"",
	"+ADDITIONAL CREDITS",
	"",
	"",
	"+SENIOR VICE PRESIDENT - STUDIOS",
	"+(and visionary extraordinaire)",
	"",
	"Mitch Lasky",
	"",
	"",
	"",
	"+EXTERNAL BETA TEST LIASON",
	"",
	"Jonathon Moses",
	"Emily Moher",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"DON'T YOU HAVE ANYTHING BETTER TO DO ?",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"+---------------------",
	"+ADDITIONAL THANKS TO:",
	"+---------------------",
	"",
	"John Tam",
	"Doug Jacobs",
	"Tim Vanlaw",
	"",
	"Xian",
	"",
	"The patience and understanding of",
	"all the spouses and girlfriends of those involved",
	"",
	"The original Heretic Team",
	"",
	"The Raven SOF team for support and playtesting",
	"",
	"All of our parents and family for their support.",
	"",
	"Blues News - www.bluesnews.com",
	"www.heretic2.com",
	"www.hereticii.com",
	"",
	"Cub Foods",
	"The 'Play 'til You Win' machine",
	"Old Chicago",
	"Caffeine",
	"",
	"Whomever decided to not call the game 'Hecatomb'",
	"",
	"Our fans, world wide, for whom we make these games.",
	"",
	"Micah Mason, Skip McIlvaine and everyone else at Aureal for",
	"helping out with the A3D system.",
	"",
	"Keith Charley and everyone at Creative for their",
	"help on EAX support.",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"+-----------------------------------",
	"+ENHANCEMENT PACK QUALITY ASSURANCE:",
	"+-----------------------------------",
	"",
	"David Baker",
	"Tom Bissel",
	"Glen Ige",
	"Ryan Krogel",
	"Matt Mclure",
	"Sam Nouriani",
	"Nadine Theuzillot",
	"Tim Vanlaw",
	"",
	"",
	"",
	"",
	"+------------------------------",
	"+ENHANCEMENT PACK BETA TESTERS:",
	"+------------------------------",
	"",
	"Anthony Affrunti",
	"Mike 'Panic[FdK]O[' Bastien",
	"Vangie 'Aurora' Beal",
	"Larry 'axeman' Blades",
	"Paul 'RitaliN' Brestelli",
	"Laura 'Anubis[FdK]O[' Carroll",
	"Andre Cerny",
	"Mark Danielson",
	"Jason 'ZeroHour' Davis",
	"Greg Floyd",
	"Andrew 'Xanadu' Forceno",
	"Chris 'DigitalDarkness' Gaboury",
	"Craig Galbraith",
	"Jay 'Anduril' Garcia",
	"David Gasior",
	"John Goff",
	"Daryle 'Griff(CT)' Griffith",
	"Joe	Griner",
	"Patrcik 'Skeeter]O[' Hamilton",
	"Randall 'legLess' Hansen",
	"David 'Chrome Tiger' Hebbe",
	"Manveer 'Eidolon' Heir",
	"Victor Henzi",
	"Shawn 'Hanzo' Holmes",
	"Erik 'Dragon' Kennedy",
	"Michael Kuczi",
	"Steve 'Crowdpleazr' Latta",
	"Micah Mason",
	"Chris 'Sgt. Shaggy' Massey",
	"Skip McIlvaine",
	"Suneil Mishra",
	"Pat 'Mestema' Misur",
	"Thomas Murray",
	"William 'Phoebus' Mull",
	"Ronnie Perez",
	"Andy Price",
	"Abraham Rahey",
	"Jon Renner",
	"Ken Rumsey",
	"Clem Golden Samuel II",
	"Paul M Sauser",
	"Brian 'Helter Skelter' Sims",
	"Sparrowslain",
	"Greg 'Alch]O[' Stanich",
	"Danny 'Bag a' Bagels' Starita",
	"Rahul C. Singhal",
	"Randall Zellner",
	"Tom V. 'Kravnos ]MK['",
	"Tyler 'BludBath' Potenberg",
	"Xtian",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"YOU MUST BE HARDCORE TO HAVE THIS MUCH PATIENCE...",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"Heretic II(tm) (C)1998 RAVEN Software, Inc.", // H2_1.07: "(C)2012"
	"All Rights Reserved.	Distributed by",
	"Activision, Inc. under license.",
	"Heretic II (tm), the RAVEN Software name,",
	"the \"Heretic II\"(tm) logo and RAVEN(tm)",
	"logo are trademarks of RAVEN Software,",
	"Quake II(tm), the Id Software name,",
	"the \"Q II\"(tm) logo and id(tm)",
	"logo are trademarks of Id Software,",
	"Inc. Activision(R) is a registered",
	"trademark of Activision, Inc. All",
	"other trademarks and trade names are",
	"properties of their respective owners.",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"The characters represented in this product are ficticious.",
	"Any resemblence to real Elves, Insectoid Creatures, or",
	"Serpent Riders, living or undead, is purely coincidental.",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"No Chickens were harmed in the making of this game.",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"+----------",
	"+HERETIC II",
	"+----------",
	"",
	"+By",
	"+The Elves In Black",
	"",
	"+Raven Software",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"ALL DONE NOW...",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"PLEASE QUIT NOW!",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"GET BACK TO PLAYING!",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"ALL RIGHT, YOU ASKED FOR IT...",
	"",
	"",
	"",
	"",
	"+-----------------",
	"+HERETIC II HAIKU:",
	"+-----------------",
	"",
	"",
	"",
	"",
	"Swift strikes prove deadly",
	"My blade moves with precision",
	"You have met your match",
	"",
	"",
	"",
	"",
	"Corvus dashes forth",
	"Sorcery pours from his hands",
	"Deep-fried G'Krokon",
	"",
	"",
	"",
	"",
	"Sickly plague-ridden",
	"carriers of fetid war",
	"They will be but sport",
	"",
	"",
	"",
	"",
	"Clicking sounds erupt",
	"in the lair of the hive queen",
	"What's a T'Chek'rik?!?",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"OKAY THAT'S ENOUGH TORTURE FOR YOU...",
	"",
	"",
	"",
	"",
	"+THANKS FOR READING!",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	NULL
};

#pragma endregion

cvar_t* m_banner_credits;

static int credits_start_time;

static void M_Credits_MenuDraw(void)
{
	paletteRGBA_t color;
	char* line;

	// Draw menu BG.
	Menu_DrawBG("book/back/b_conback8.bk", cls.m_menuscale);

	// Draw credits.
	int y = viddef.height - (cls.realtime - credits_start_time) / 24; //mxd. / 40 in original logic. Make it scroll a bit faster...
	for (int i = 0; raven_credits[i] != NULL && y < viddef.height; i++, y += ui_line_height)
	{
		if (y <= -ui_char_size)
			continue;

		if (raven_credits[i][0] == '+')
		{
			line = raven_credits[i] + 1;
			color = TextPalette[P_CRED_TITLE];
		}
		else
		{
			line = raven_credits[i];
			color = TextPalette[P_CRED_CONTENT];
		}

		const int x = (viddef.width - ui_char_size * (int)strlen(line)) / 2;
		color.a = (byte)(cls.m_menualpha * 255.0f);
		DrawString(x, y, line, color, -1);
	}

	if (y < 0 && cls.m_menustate == 2)
		M_PopMenu();
}

//TODO: implement 'cheer' and 'celebrate' buttons.
static const char* M_Credits_Key(const int key)
{
	if (cls.m_menustate == 2 && key == K_ESCAPE)
		M_PopMenu();

	//TODO: scroll credits 2x faster when K_SPACE is pressed?
	return NULL;
}

void M_Menu_Credits_f(void)
{
	credits_start_time = cls.realtime;
	M_PushMenu(M_Credits_MenuDraw, M_Credits_Key);
	Cbuf_AddText("cd loop 2\n");
	Cbuf_Execute();
}