//
// g_save_defs.c -- generated by H2RSaveDefGenApp. Do modify.
//
// Copyright 2025 m-x-d
//

#pragma region ================================ HUGE INCLUDES LIST ================================

#include "g_save_defs.h"
#include "c_corvus1_moves.h"
#include "c_corvus2_moves.h"
#include "c_corvus3_moves.h"
#include "c_corvus4_moves.h"
#include "c_corvus5_moves.h"
#include "c_corvus6_moves.h"
#include "c_corvus7_moves.h"
#include "c_corvus8_moves.h"
#include "c_corvus9_moves.h"
#include "c_dranor_moves.h"
#include "c_elflord_moves.h"
#include "c_morcalavin_moves.h"
#include "c_priestess2_moves.h"
#include "c_priestess_moves.h"
#include "c_siernan1_moves.h"
#include "c_siernan2_moves.h"
#include "c_ssithrascout_moves.h"
#include "c_tome_moves.h"
#include "c_victimssithra_moves.h"
#include "g_breakable.h"
#include "g_func_Door.h"
#include "g_func_Train.h"
#include "g_func_Utility.h"
#include "g_light.h"
#include "g_monster.h"
#include "g_obj.h"
#include "g_target.h"
#include "m_assassin_moves.h"
#include "m_beast_moves.h"
#include "m_chicken_moves.h"
#include "m_elflord_moves.h"
#include "m_fish_moves.h"
#include "m_gkrokon_moves.h"
#include "m_gorgon_moves.h"
#include "m_harpy_moves.h"
#include "m_imp_moves.h"
#include "m_morcalavin_moves.h"
#include "m_mother_moves.h"
#include "m_mssithra_moves.h"
#include "m_ogle_moves.h"
#include "m_plagueElf_moves.h"
#include "m_plaguesSithra_moves.h"
#include "m_priestess_moves.h"
#include "m_rat_moves.h"
#include "m_seraph_guard_moves.h"
#include "m_seraph_moves.h"
#include "m_spreader_moves.h"
#include "m_tcheckrik_moves.h"
#include "p_teleport.h"
#include "g_debris.h"
#include "g_DefaultMessageHandler.h"
#include "g_env.h"
#include "g_field.h"
#include "g_flamethrower.h"
#include "g_func_Button.h"
#include "g_func_MonsterSpawner.h"
#include "g_func_Plat.h"
#include "g_func_Rotating.h"
#include "g_func_Timer.h"
#include "g_items.h"
#include "g_misc.h"
#include "g_morcalavin_barrier.h"
#include "g_rope.h"
#include "g_Shrine.h"
#include "g_trigger.h"
#include "g_utils.h"
#include "g_waterfx.h"
#include "mg_ai.h"
#include "mg_guide.h"
#include "m_assassin.h"
#include "m_beast.h"
#include "m_chicken.h"
#include "m_elflord.h"
#include "m_fish.h"
#include "m_gkrokon.h"
#include "m_gorgon.h"
#include "m_harpy.h"
#include "m_imp.h"
#include "m_morcalavin.h"
#include "m_mssithra.h"
#include "m_ogle.h"
#include "m_plagueElf.h"
#include "m_plaguesSithra.h"
#include "m_priestess.h"
#include "m_rat.h"
#include "m_seraph.h"
#include "m_seraph_guard.h"
#include "m_spreader.h"
#include "m_spreadermist.h"
#include "m_tcheckrik.h"
#include "m_tcheckrik_spells.h"
#include "p_client.h"
#include "p_morph.h"
#include "sc_Main.h"
#include "spl_BlueRing.h"
#include "spl_flyingfist.h"
#include "spl_HellStaff.h"
#include "spl_maceballs.h"
#include "spl_magicmissile.h"
#include "spl_meteorbarrier.h"
#include "spl_morph.h"
#include "spl_Phoenix.h"
#include "spl_RedRain.h"
#include "spl_ripper.h"
#include "spl_sphereofannihlation.h"
#include "spl_tornado.h"
#include "spl_wall.h"

#pragma endregion

#pragma region ================================ FUNCS LIST ================================

const func_map_t funcs_list[] =
{
	// buoy.c:
	{ "LinkBuoyInfo",						(byte*)LinkBuoyInfo },

	// g_breakable.c:
	{ "BreakableBrushUse",					(byte*)BreakableBrushUse },
	{ "LinkBreakableBrushesThink",			(byte*)LinkBreakableBrushesThink },

	// g_debris.c:
	{ "BecomeDebris",						(byte*)BecomeDebris },

	// g_DefaultMessageHandler.c:
	{ "G_FreeEdict",						(byte*)G_FreeEdict },

	// g_env.c:
	{ "EnvDustUse",							(byte*)EnvDustUse },
	{ "EnvSmokeUse",						(byte*)EnvSmokeUse },
	{ "EnvSunInitThink",					(byte*)EnvSunInitThink },

	// g_field.c:
	{ "FogDensityTouch",					(byte*)FogDensityTouch },
	{ "TriggerDamageTouch",					(byte*)TriggerDamageTouch },
	{ "TriggerDamageUse",					(byte*)TriggerDamageUse },
	{ "TriggerGotoBuoyTouch",				(byte*)TriggerGotoBuoyTouch },
	{ "TriggerGotoBuoyTouchThink",			(byte*)TriggerGotoBuoyTouchThink },
	{ "TriggerGotoBuoyUse",					(byte*)TriggerGotoBuoyUse },
	{ "TriggerGotoBuoyUseThink",			(byte*)TriggerGotoBuoyUseThink },
	{ "TriggerGravityTouch",				(byte*)TriggerGravityTouch },
	{ "TriggerMonsterJumpTouch",			(byte*)TriggerMonsterJumpTouch },
	{ "TriggerPushActivated",				(byte*)TriggerPushActivated },
	{ "TriggerPushTouch",					(byte*)TriggerPushTouch },

	// g_flamethrower.c:
	{ "FlamethrowerThink",					(byte*)FlamethrowerThink },
	{ "FlamethrowerTouch",					(byte*)FlamethrowerTouch },
	{ "FlamethrowerUse",					(byte*)FlamethrowerUse },

	// g_func_Button.c:
	{ "FuncButtonReturn",					(byte*)FuncButtonReturn },
	{ "FuncButtonTouch",					(byte*)FuncButtonTouch },
	{ "FuncButtonUse",						(byte*)FuncButtonUse },
	{ "FuncButtonDone",						(byte*)FuncButtonDone },	// Indirectly used as moveinfo.endfunc --mxd.
	{ "FuncButtonWait",						(byte*)FuncButtonWait },	// Indirectly used as moveinfo.endfunc --mxd.

	// g_func_Door.c:
	{ "FuncDoorBlocked",					(byte*)FuncDoorBlocked },
	{ "FuncDoorCalcMoveSpeedThink",			(byte*)FuncDoorCalcMoveSpeedThink },
	{ "FuncDoorDie",						(byte*)FuncDoorDie },
	{ "FuncDoorGoDown",						(byte*)FuncDoorGoDown },
	{ "FuncDoorSecretBlocked",				(byte*)FuncDoorSecretBlocked },
	{ "FuncDoorSecretDie",					(byte*)FuncDoorSecretDie },
	{ "FuncDoorSecretMove2",				(byte*)FuncDoorSecretMove2 },
	{ "FuncDoorSecretMove4",				(byte*)FuncDoorSecretMove4 },
	{ "FuncDoorSecretMove6",				(byte*)FuncDoorSecretMove6 },
	{ "FuncDoorSecretUse",					(byte*)FuncDoorSecretUse },
	{ "FuncDoorSpawnDoorTriggerThink",		(byte*)FuncDoorSpawnDoorTriggerThink },
	{ "FuncDoorTouch",						(byte*)FuncDoorTouch },
	{ "FuncDoorTriggerTouch",				(byte*)FuncDoorTriggerTouch },
	{ "FuncDoorUse",						(byte*)FuncDoorUse },
	{ "FuncDoorHitBottom",					(byte*)FuncDoorHitBottom },		// Indirectly used as moveinfo.endfunc --mxd.
	{ "FuncDoorHitTop",						(byte*)FuncDoorHitTop },		// Indirectly used as moveinfo.endfunc --mxd.
	{ "FuncDoorSecretMove1",				(byte*)FuncDoorSecretMove1 },	// Indirectly used as moveinfo.endfunc --mxd.
	{ "FuncDoorSecretMove3",				(byte*)FuncDoorSecretMove3 },	// Indirectly used as moveinfo.endfunc --mxd.
	{ "FuncDoorSecretMove5",				(byte*)FuncDoorSecretMove5 },	// Indirectly used as moveinfo.endfunc --mxd.
	{ "FuncDoorSecretDone",					(byte*)FuncDoorSecretDone },	// Indirectly used as moveinfo.endfunc --mxd.

	// g_func_MonsterSpawner.c:
	{ "FuncMonsterSpawnerGo",				(byte*)FuncMonsterSpawnerGo },
	{ "FuncMonsterSpawnerUse",				(byte*)FuncMonsterSpawnerUse },

	// g_func_Plat.c:
	{ "FuncPlatBlocked",					(byte*)FuncPlatBlocked },
	{ "FuncPlatCenterTouch",				(byte*)FuncPlatCenterTouch },
	{ "FuncPlatGoDown",						(byte*)FuncPlatGoDown },
	{ "FuncPlatUse",						(byte*)FuncPlatUse },
	{ "FuncPlatHitBottom",					(byte*)FuncPlatHitBottom },	// Indirectly used as moveinfo.endfunc --mxd.
	{ "FuncPlatHitTop",						(byte*)FuncPlatHitTop },	// Indirectly used as moveinfo.endfunc --mxd.

	// g_func_Rotating.c:
	{ "FuncRotatingBlocked",				(byte*)FuncRotatingBlocked },
	{ "FuncRotatingTouch",					(byte*)FuncRotatingTouch },
	{ "FuncRotatingUse",					(byte*)FuncRotatingUse },

	// g_func_Timer.c:
	{ "FuncTimerThink",						(byte*)FuncTimerThink },
	{ "FuncTimerUse",						(byte*)FuncTimerUse },

	// g_func_Train.c:
	{ "FuncTrainAnim",						(byte*)FuncTrainAnim },
	{ "FuncTrainAnimBackwards",				(byte*)FuncTrainAnimBackwards },
	{ "FuncTrainBlocked",					(byte*)FuncTrainBlocked },
	{ "FuncTrainFind",						(byte*)FuncTrainFind },
	{ "FuncTrainNext",						(byte*)FuncTrainNext },
	{ "FuncTrainUse",						(byte*)FuncTrainUse },
	{ "FuncTrainWait",						(byte*)FuncTrainWait },	// Indirectly used as moveinfo.endfunc --mxd.

	// g_func_Utility.c:
	{ "AccelMoveThink",						(byte*)AccelMoveThink },
	{ "AngleMoveBegin",						(byte*)AngleMoveBegin },
	{ "AngleMoveDone",						(byte*)AngleMoveDone },
	{ "AngleMoveFinal",						(byte*)AngleMoveFinal },
	{ "MoveBegin",							(byte*)MoveBegin },
	{ "MoveDone",							(byte*)MoveDone },
	{ "MoveFinal",							(byte*)MoveFinal },

	// g_items.c:
	{ "DoRespawn",							(byte*)DoRespawn },
	{ "DropItemMakeTouchable",				(byte*)DropItemMakeTouchable },
	{ "ItemDropToFloor",					(byte*)ItemDropToFloor },
	{ "PreRespawnThink",					(byte*)PreRespawnThink },
	{ "RespawnedThink",						(byte*)RespawnedThink },
	{ "Touch_Item",							(byte*)Touch_Item },

	// g_light.c:
	{ "EnvFireMoveThink",					(byte*)EnvFireMoveThink },
	{ "EnvFireUse",							(byte*)EnvFireUse },
	{ "FlameDamagerTouch",					(byte*)FlameDamagerTouch },
	{ "LightUse",							(byte*)LightUse },
	{ "TorchStart",							(byte*)TorchStart },
	{ "TorchUse",							(byte*)TorchUse },

	// g_misc.c:
	{ "FuncAreaportalUse",					(byte*)FuncAreaportalUse },
	{ "FuncObjectRelease",					(byte*)FuncObjectRelease },
	{ "FuncObjectTouch",					(byte*)FuncObjectTouch },
	{ "FuncObjectUse",						(byte*)FuncObjectUse },
	{ "FuncWallUse",						(byte*)FuncWallUse },
	{ "ItemSpitterUse",						(byte*)ItemSpitterUse },
	{ "MiscFireSparkerRemove",				(byte*)MiscFireSparkerRemove },
	{ "MiscFireSparkerThink",				(byte*)MiscFireSparkerThink },
	{ "MiscFireSparkerUse",					(byte*)MiscFireSparkerUse },
	{ "MiscFlagThink",						(byte*)MiscFlagThink },
	{ "MiscMagicPortalTouch",				(byte*)MiscMagicPortalTouch },
	{ "MiscMagicPortalUse",					(byte*)MiscMagicPortalUse },
	{ "MiscRemoteCameraThink",				(byte*)MiscRemoteCameraThink },
	{ "MiscRemoteCameraUse",				(byte*)MiscRemoteCameraUse },
	{ "MiscUpdateSpawnerTouch",				(byte*)MiscUpdateSpawnerTouch },
	{ "PathCornerTouch",					(byte*)PathCornerTouch },
	{ "PointCombatTouch",					(byte*)PointCombatTouch },
	{ "SoundAmbientThink",					(byte*)SoundAmbientThink },
	{ "SoundAmbientUse",					(byte*)SoundAmbientUse },
	
	// g_monster.c:
	{ "GenericMonsterAlerted",				(byte*)GenericMonsterAlerted },
	{ "M_CheckAttack",						(byte*)M_CheckAttack },
	{ "M_DeadBobThink",						(byte*)M_DeadBobThink },
	{ "M_DeadFloatThink",					(byte*)M_DeadFloatThink },
	{ "M_DropToFloor",						(byte*)M_DropToFloor },
	{ "M_EndDeath",							(byte*)M_EndDeath },
	{ "M_FlymonsterStartGo",				(byte*)M_FlymonsterStartGo },
	{ "M_MoveFrame",						(byte*)M_MoveFrame },
	{ "M_Think",							(byte*)M_Think },
	{ "M_Touch",							(byte*)M_Touch },
	{ "M_TriggeredSpawnThink",				(byte*)M_TriggeredSpawnThink },
	{ "M_TriggeredSpawnUse",				(byte*)M_TriggeredSpawnUse },
	{ "M_Use",								(byte*)M_Use },
	{ "M_WalkmonsterStartGo",				(byte*)M_WalkmonsterStartGo },

	// g_morcalavin_barrier.c:
	{ "MorcalavinBarrierThink",				(byte*)MorcalavinBarrierThink },
	{ "MorcalavinBarrierTouch",				(byte*)MorcalavinBarrierTouch },
	{ "MorcalavinBarrierUse",				(byte*)MorcalavinBarrierUse },

	// g_obj.c:
	{ "ObjBarrelDie",						(byte*)ObjBarrelDie },
	{ "ObjBarrelExplodeThink",				(byte*)ObjBarrelExplodeThink },
	{ "ObjBiotankContentsAnimThink",		(byte*)ObjBiotankContentsAnimThink },
	{ "ObjBiotankTouch",					(byte*)ObjBiotankTouch },
	{ "ObjCactus4CloseThink",				(byte*)ObjCactus4CloseThink },
	{ "ObjCactus4OpenThink",				(byte*)ObjCactus4OpenThink },
	{ "ObjCactus4Use",						(byte*)ObjCactus4Use },
	{ "ObjCactusTouch",						(byte*)ObjCactusTouch },
	{ "ObjChest1AnimThink",					(byte*)ObjChest1AnimThink },
	{ "ObjChest1Use",						(byte*)ObjChest1Use },
	{ "ObjCog1AnimThink",					(byte*)ObjCog1AnimThink },
	{ "ObjCog1Use",							(byte*)ObjCog1Use },
	{ "ObjDyingElfDie",						(byte*)ObjDyingElfDie },
	{ "ObjDyingElfIdleThink",				(byte*)ObjDyingElfIdleThink },
	{ "ObjDyingElfPain",					(byte*)ObjDyingElfPain },
	{ "ObjDyingElfReachAnimThink",			(byte*)ObjDyingElfReachAnimThink },
	{ "ObjDyingElfTouch",					(byte*)ObjDyingElfTouch },
	{ "ObjHangingOgleMoanThink",			(byte*)ObjHangingOgleMoanThink },
	{ "ObjHivePriestessSymbolThink",		(byte*)ObjHivePriestessSymbolThink },
	{ "ObjHivePriestessSymbolUse",			(byte*)ObjHivePriestessSymbolUse },
	{ "ObjLarvaAnimThink",					(byte*)ObjLarvaAnimThink },
	{ "ObjLarvaTouch",						(byte*)ObjLarvaTouch },
	{ "ObjLeverDownThink",					(byte*)ObjLeverDownThink },
	{ "ObjLeverUpThink",					(byte*)ObjLeverUpThink },
	{ "ObjLeverUse",						(byte*)ObjLeverUse },
	{ "ObjSeasonglobeBottomThink",			(byte*)ObjSeasonglobeBottomThink },
	{ "ObjSeasonglobeBottomUse",			(byte*)ObjSeasonglobeBottomUse },
	{ "ObjSeasonglobeTopThink",				(byte*)ObjSeasonglobeTopThink },
	{ "ObjSeasonglobeTopUse",				(byte*)ObjSeasonglobeTopUse },
	{ "ObjSpellbookAnimThink",				(byte*)ObjSpellbookAnimThink },
	{ "ObjSpellbookUse",					(byte*)ObjSpellbookUse },
	{ "ObjStatueSsithraGuardThink",			(byte*)ObjStatueSsithraGuardThink },
	{ "ObjStatueSsithraGuardUse",			(byte*)ObjStatueSsithraGuardUse },
	{ "ObjStatueTchecktrikBustUse",			(byte*)ObjStatueTchecktrikBustUse },
	{ "ObjStatueTecheckrikTombUse",			(byte*)ObjStatueTecheckrikTombUse },
	{ "ObjStatueTecheckrikUse",				(byte*)ObjStatueTecheckrikUse },
	{ "ObjTortureIronmaidenClose",			(byte*)ObjTortureIronmaidenClose },
	{ "ObjTortureIronmaidenOpen",			(byte*)ObjTortureIronmaidenOpen },
	{ "ObjTortureIronmaidenTouch",			(byte*)ObjTortureIronmaidenTouch },
	{ "ObjTortureIronmaidenUse",			(byte*)ObjTortureIronmaidenUse },
	{ "PushableObjectTouch",				(byte*)PushableObjectTouch },

	// g_rope.c:
	{ "ObjRopeThink",						(byte*)ObjRopeThink },
	{ "ObjRopeTouch",						(byte*)ObjRopeTouch },
	{ "TutorialChickenPain",				(byte*)TutorialChickenPain },
	{ "TutorialChickenRopeEndThink",		(byte*)TutorialChickenRopeEndThink },
	{ "TutorialChickenThink",				(byte*)TutorialChickenThink },
	{ "TutorialChickenUse",					(byte*)TutorialChickenUse },

	// g_shrine.c:
	{ "ShrineArmorGoldTouch",				(byte*)ShrineArmorGoldTouch },
	{ "ShrineArmorSilverTouch",				(byte*)ShrineArmorSilverTouch },
	{ "ShrineDelayThink",					(byte*)ShrineDelayThink },
	{ "ShrineGhostTouch",					(byte*)ShrineGhostTouch },
	{ "ShrineHealTouch",					(byte*)ShrineHealTouch },
	{ "ShrineLightTouch",					(byte*)ShrineLightTouch },
	{ "ShrineLungsTouch",					(byte*)ShrineLungsTouch },
	{ "ShrineManaTouch",					(byte*)ShrineManaTouch },
	{ "ShrinePowerupTouch",					(byte*)ShrinePowerupTouch },
	{ "ShrineRandomTouch",					(byte*)ShrineRandomTouch },
	{ "ShrineReflectTouch",					(byte*)ShrineReflectTouch },
	{ "ShrineSpeedTouch",					(byte*)ShrineSpeedTouch },
	{ "ShrineStaffTouch",					(byte*)ShrineStaffTouch },

	// g_target.c:
	{ "TargetChangelevelUse",				(byte*)TargetChangelevelUse },
	{ "TargetCrosslevelTargetThink",		(byte*)TargetCrosslevelTargetThink },
	{ "TargetCrosslevelTriggerUse",			(byte*)TargetCrosslevelTriggerUse },
	{ "TargetEarthquakeThink",				(byte*)TargetEarthquakeThink },
	{ "TargetEarthquakeUse",				(byte*)TargetEarthquakeUse },
	{ "TargetExplosionExplodeThink",		(byte*)TargetExplosionExplodeThink },
	{ "TargetExplosionUse",					(byte*)TargetExplosionUse },
	{ "TargetLightrampThink",				(byte*)TargetLightrampThink },
	{ "TargetLightrampUse",					(byte*)TargetLightrampUse },
	{ "TargetTempEntityUse",				(byte*)TargetTempEntityUse },

	// g_trigger.c:
	{ "ChooseCDTrackTouch",					(byte*)ChooseCDTrackTouch },
	{ "ChooseCDTrackUse",					(byte*)ChooseCDTrackUse },
	{ "KillSoundThink",						(byte*)KillSoundThink },
	{ "TriggerActivateActivated",			(byte*)TriggerActivateActivated },
	{ "TriggerCounterUse",					(byte*)TriggerCounterUse },
	{ "TriggerDeactivateActivated",			(byte*)TriggerDeactivateActivated },
	{ "TriggerElevatorInitThink",			(byte*)TriggerElevatorInitThink },
	{ "TriggerElevatorUse",					(byte*)TriggerElevatorUse },
	{ "TriggerEnable",						(byte*)TriggerEnable },
	{ "TriggerEndgameThink",				(byte*)TriggerEndgameThink },
	{ "TriggerEndgameTouch",				(byte*)TriggerEndgameTouch },
	{ "TriggerEndgameUse",					(byte*)TriggerEndgameUse },
	{ "TriggerFarclipTouch",				(byte*)TriggerFarclipTouch },
	{ "TriggerLightningActivated",			(byte*)TriggerLightningActivated },
	{ "TriggerLightningUse",				(byte*)TriggerLightningUse },
	{ "TriggerMappercentageUse",			(byte*)TriggerMappercentageUse },
	{ "TriggerMissionGiveUse",				(byte*)TriggerMissionGiveUse },
	{ "TriggerMissionTakeUse",				(byte*)TriggerMissionTakeUse },
	{ "TriggerMultipleTouch",				(byte*)TriggerMultipleTouch },
	{ "TriggerMultipleUse",					(byte*)TriggerMultipleUse },
	{ "TriggerMultipleWaitThink",			(byte*)TriggerMultipleWaitThink },
	{ "TriggerPlayerPushButtonTouch",		(byte*)TriggerPlayerPushButtonTouch },
	{ "TriggerPlayerPushLeverActivated",	(byte*)TriggerPlayerPushLeverActivated },
	{ "TriggerPlayerUsePuzzleActivated",	(byte*)TriggerPlayerUsePuzzleActivated },
	{ "TriggerPuzzleUse",					(byte*)TriggerPuzzleUse },
	{ "TriggerQuakeActivated",				(byte*)TriggerQuakeActivated },
	{ "TriggerQuitToMenuTouch",				(byte*)TriggerQuitToMenuTouch },
	{ "TriggerQuitToMenuUse",				(byte*)TriggerQuitToMenuUse },
	{ "TriggerRelayUse",					(byte*)TriggerRelayUse },

	// g_utils.c:
	{ "DelayThink",							(byte*)DelayThink },
	{ "G_SetToFree",						(byte*)G_SetToFree },
	{ "G_UseTargets",						(byte*)G_UseTargets },

	// g_waterfx.c:
	{ "EnvWaterDripThink",					(byte*)EnvWaterDripThink },
	{ "EnvWaterDripUse",					(byte*)EnvWaterDripUse },
	{ "EnvWaterFountainUse",				(byte*)EnvWaterFountainUse },

	// mg_ai.c:
	{ "BodyPhaseOutPostThink",				(byte*)BodyPhaseOutPostThink },
	{ "MG_PostDeathThink",					(byte*)MG_PostDeathThink },

	// mg_guide.c:
	{ "MG_GenericMoodSet",					(byte*)MG_GenericMoodSet },

	// m_assassin.c:
	{ "AssassinBlocked",					(byte*)AssassinBlocked },
	{ "AssassinCheckDefenseThink",			(byte*)AssassinCheckDefenseThink },
	{ "AssassinCloakFadePreThink",			(byte*)AssassinCloakFadePreThink },
	{ "AssassinCloakPreThink",				(byte*)AssassinCloakPreThink },
	{ "AssassinDaggerTouch",				(byte*)AssassinDaggerTouch },
	{ "AssassinDeCloakFadePreThink",		(byte*)AssassinDeCloakFadePreThink },
	{ "AssassinDismember",					(byte*)AssassinDismember },

	// m_beast.c:
	{ "TBeastBlocked",						(byte*)TBeastBlocked },
	{ "TBeastDieUse",						(byte*)TBeastDieUse },
	{ "TBeastPostThink",					(byte*)TBeastPostThink },
	{ "TBeastTouch",						(byte*)TBeastTouch },
	{ "TBeastUse",							(byte*)TBeastUse },

	// m_chicken.c:
	{ "MorphChickenOut",					(byte*)MorphChickenOut },
	{ "MorphOriginalIn",					(byte*)MorphOriginalIn },

	// m_elflord.c:
	{ "ElfLordPreThink",					(byte*)ElfLordPreThink },
	{ "ElfLordProjectileBlocked",			(byte*)ElfLordProjectileBlocked },

	// m_fish.c:
	{ "FishIsBlocked",						(byte*)FishIsBlocked },
	{ "FishThink",							(byte*)FishThink },

	// m_gkrokon.c:
	{ "GkrokonDismember",					(byte*)GkrokonDismember },
	{ "GkrokonSpooIsBlocked",				(byte*)GkrokonSpooIsBlocked },
	{ "GkrokonSpooTouch",					(byte*)GkrokonSpooTouch },

	// m_gorgon.c:
	{ "GorgonPreThink",						(byte*)GorgonPreThink },
	{ "GorgonRoarResponsePreThink",			(byte*)GorgonRoarResponsePreThink },

	// m_harpy.c:
	{ "HarpyDismember",						(byte*)HarpyDismember },
	{ "HarpyHeadDie",						(byte*)HarpyHeadDie },
	{ "HarpyHeadThink",						(byte*)HarpyHeadThink },
	{ "HarpyIsBlocked",						(byte*)HarpyIsBlocked },

	// m_imp.c:
	{ "ImpFireballBlocked",					(byte*)ImpFireballBlocked },
	{ "ImpIsBlocked",						(byte*)ImpIsBlocked },

	// m_morcalavin.c:
	{ "MorcalavinBeamIsBlocked",			(byte*)MorcalavinBeamIsBlocked },
	{ "MorcalavinBeamThink",				(byte*)MorcalavinBeamThink },
	{ "MorcalavinDie",						(byte*)MorcalavinDie },
	{ "MorcalavinLaughPostThink",			(byte*)MorcalavinLaughPostThink },
	{ "MorcalavinLightning2Think",			(byte*)MorcalavinLightning2Think },
	{ "MorcalavinLightningThink",			(byte*)MorcalavinLightningThink },
	{ "MorcalavinMissileThink",				(byte*)MorcalavinMissileThink },
	{ "MorcalavinPhaseInPreThink",			(byte*)MorcalavinPhaseInPreThink },
	{ "MorcalavinPhaseOutPreThink",			(byte*)MorcalavinPhaseOutPreThink },
	{ "MorcalavinPostThink",				(byte*)MorcalavinPostThink },
	{ "MorcalavinProjectile1Blocked",		(byte*)MorcalavinProjectile1Blocked },
	{ "MorcalavinProjectile2Blocked",		(byte*)MorcalavinProjectile2Blocked },
	{ "MorcalavinProjectile3Blocked",		(byte*)MorcalavinProjectile3Blocked },
	{ "MorcalavinTrackingProjectileThink",	(byte*)MorcalavinTrackingProjectileThink },

	// m_mssithra.c:
	{ "MssithraArrowExplodeThink",			(byte*)MssithraArrowExplodeThink },
	{ "MssithraArrowTouch",					(byte*)MssithraArrowTouch },
	{ "MssithraPostThink",					(byte*)MssithraPostThink },

	// m_ogle.c:
	{ "OgleDismember",						(byte*)OgleDismember },
	{ "OgleInitOverlordThink",				(byte*)OgleInitOverlordThink },
	{ "OgleMoodThink",						(byte*)OgleMoodThink },
	{ "OgleStartPushUse",					(byte*)OgleStartPushUse },
	{ "OgleUse",							(byte*)OgleUse },

	// m_plagueElf.c:
	{ "PlagueElfDismember",					(byte*)PlagueElfDismember },
	{ "PlagueElfPhaseInPreThink",			(byte*)PlagueElfPhaseInPreThink },
	{ "PlagueElfPhaseOutPreThink",			(byte*)PlagueElfPhaseOutPreThink },
	{ "PlagueElfSpellTouch",				(byte*)PlagueElfSpellTouch },

	// m_plagueSsithra.c:
	{ "SsithraAlert",						(byte*)SsithraAlert },
	{ "SsithraArrowExplodeThink",			(byte*)SsithraArrowExplodeThink },
	{ "SsithraArrowTouch",					(byte*)SsithraArrowTouch },
	{ "SsithraBlocked",						(byte*)SsithraBlocked },
	{ "SsithraDismember",					(byte*)SsithraDismember },
	{ "SsithraDuckArrowTouch",				(byte*)SsithraDuckArrowTouch },
	{ "SsithraSlideFallThink",				(byte*)SsithraSlideFallThink },
	{ "SsithraSlideOffThink",				(byte*)SsithraSlideOffThink },

	// m_priestess.c:
	{ "PriestessPostThink",					(byte*)PriestessPostThink },
	{ "PriestessProjectile1Blocked",		(byte*)PriestessProjectile1Blocked },
	{ "PriestessProjectile1DrunkenThink",	(byte*)PriestessProjectile1DrunkenThink },
	{ "PriestessProjectile1Think",			(byte*)PriestessProjectile1Think },
	{ "PriestessProjectile2Die",			(byte*)PriestessProjectile2Die },
	{ "PriestessProjectile2Think",			(byte*)PriestessProjectile2Think },

	// m_rat.c:
	{ "RatTouch",							(byte*)RatTouch },
	{ "RatUse",								(byte*)RatUse },

	// m_seraph.c:
	{ "SeraphAlert",						(byte*)SeraphAlert },
	{ "SeraphDismember",					(byte*)SeraphDismember },

	// m_seraph_guard.c:
	{ "SeraphGuardDismember",				(byte*)SeraphGuardDismember },
	{ "SeraphGuardProjectileBlocked",		(byte*)SeraphGuardProjectileBlocked },
	{ "SeraphGuardProjectileThink",			(byte*)SeraphGuardProjectileThink },

	// m_spreader.c:
	{ "SpreaderDismember",					(byte*)SpreaderDismember },
	{ "SpreaderDropDownThink",				(byte*)SpreaderDropDownThink },
	{ "SpreaderIsBlocked",					(byte*)SpreaderIsBlocked },
	{ "SpreaderSplatWhenBlocked",			(byte*)SpreaderSplatWhenBlocked },
	{ "SpreaderStopWhenBlocked",			(byte*)SpreaderStopWhenBlocked },

	// m_spreadermist.c:
	{ "RadiusDamageEntThink",				(byte*)RadiusDamageEntThink },
	{ "SpreaderGrenadeBounced",				(byte*)SpreaderGrenadeBounced },
	{ "SpreaderGrenadeAppearThink",			(byte*)SpreaderGrenadeAppearThink }, //mxd
	{ "SpreaderGrenadeDieThink",			(byte*)SpreaderGrenadeDieThink },
	{ "SpreaderGrenadeThink",				(byte*)SpreaderGrenadeThink },

	// m_tcheckrik.c:
	{ "TcheckrikDismember",					(byte*)TcheckrikDismember },

	// m_tcheckrik_spells.c:
	{ "InsectGlobeOfOuchinessGrowThink",	(byte*)InsectGlobeOfOuchinessGrowThink },
	{ "InsectSpearProjectileTouch",			(byte*)InsectSpearProjectileTouch },
	{ "InsectStaffBoltThink",				(byte*)InsectStaffBoltThink },
	{ "InsectStaffBoltTouch",				(byte*)InsectStaffBoltTouch },
	{ "InsectTrackingSpearProjectileThink",	(byte*)InsectTrackingSpearProjectileThink },

	// p_client.c:
	{ "BleederThink",						(byte*)BleederThink },
	{ "PlayerBodyDie",						(byte*)PlayerBodyDie },
	{ "PlayerDie",							(byte*)PlayerDie },
	{ "PlayerPain",							(byte*)PlayerPain },

	// p_morph.c:
	{ "ChickenPlayerThink",					(byte*)ChickenPlayerThink },

	// p_teleport.c
	{ "PlayerTeleporterTouch",				(byte*)PlayerTeleporterTouch },

	// sc_Main.cpp
	{ "ScriptUse",							(byte*)ScriptUse },

	// sc_Utility.cpp
	{ "animate_signaler",					(byte*)animate_signaler },

	// spl_BlueRing.c:
	{ "RingThink",							(byte*)RingThink },

	// spl_flyingfist.c:
	{ "FlyingFistFizzleThink",				(byte*)FlyingFistFizzleThink },
	{ "FlyingFistInitThink",				(byte*)FlyingFistInitThink },
	{ "FlyingFistTouch",					(byte*)FlyingFistTouch },

	// spl_HellStaff.c:
	{ "HellboltThink",						(byte*)HellboltThink },
	{ "HellboltTouch",						(byte*)HellboltTouch },

	// spl_maceballs.c:
	{ "MaceballBounce",						(byte*)MaceballBounce },
	{ "MaceballThink",						(byte*)MaceballThink },

	// spl_magicmissile.c:
	{ "MagicMissileThink",					(byte*)MagicMissileThink },
	{ "MagicMissileTouch",					(byte*)MagicMissileTouch },

	// spl_meteorbarrier.c:
	{ "Kill_Meteor",						(byte*)Kill_Meteor },
	{ "MeteorBarrierBounceThink",			(byte*)MeteorBarrierBounceThink },
	{ "MeteorBarrierHuntThink",				(byte*)MeteorBarrierHuntThink },
	{ "MeteorBarrierOnBlocked",				(byte*)MeteorBarrierOnBlocked },
	{ "MeteorBarrierSearchInitThink",		(byte*)MeteorBarrierSearchInitThink },
	{ "MeteorBarrierSearchThink",			(byte*)MeteorBarrierSearchThink },

	// spl_morph.c:
	{ "MonsterMorphFadeIn",					(byte*)MonsterMorphFadeIn },
	{ "MonsterMorphFadeOut",				(byte*)MonsterMorphFadeOut },
	{ "MorphMissileThink",					(byte*)MorphMissileThink },
	{ "MorphMissileTouch",					(byte*)MorphMissileTouch },

	// spl_Phoenix.c:
	{ "PhoenixMissileThink",				(byte*)PhoenixMissileThink },
	{ "PhoenixMissileTouch",				(byte*)PhoenixMissileTouch },

	// spl_RedRain.c:
	{ "RedRainMissileThink",				(byte*)RedRainMissileThink },
	{ "RedRainMissileTouch",				(byte*)RedRainMissileTouch },
	{ "RedRainRemove",						(byte*)RedRainRemove },
	{ "RedRainThink",						(byte*)RedRainThink },

	// spl_ripper.c:
	{ "RipperExplodeBallThink",				(byte*)RipperExplodeBallThink },
	{ "RipperExplodeBallTouch",				(byte*)RipperExplodeBallTouch },

	// spl_sphereofannihlation.c:
	{ "SphereExplodeThink",					(byte*)SphereExplodeThink },
	{ "SphereOfAnnihilationGrowThink",		(byte*)SphereOfAnnihilationGrowThink },
	{ "SphereOfAnnihilationGrowThinkPower",	(byte*)SphereOfAnnihilationGrowThinkPower },
	{ "SphereOfAnnihilationTouch",			(byte*)SphereOfAnnihilationTouch },
	{ "SpherePowerLaserThink",				(byte*)SpherePowerLaserThink },
	{ "SpherePowerLaserTouch",				(byte*)SpherePowerLaserTouch },
	{ "SphereWatcherFlyThink",				(byte*)SphereWatcherFlyThink },
	{ "SphereWatcherGrowThink",				(byte*)SphereWatcherGrowThink },
	{ "SphereWatcherTouch",					(byte*)SphereWatcherTouch },

	// spl_tornado.c:
	{ "TornadoCreateThink",					(byte*)TornadoCreateThink },
	{ "TornadoThink",						(byte*)TornadoThink },

	// spl_wall.c:
	{ "FireBlastBlocked",					(byte*)FireBlastBlocked },
	{ "FireBlastStartThink",				(byte*)FireBlastStartThink },
	{ "FireBlastThink",						(byte*)FireBlastThink },
	{ "FireWallMissileBlocked",				(byte*)FireWallMissileBlocked },
	{ "FireWallMissileStartThink",			(byte*)FireWallMissileStartThink },
	{ "FireWallMissileThink",				(byte*)FireWallMissileThink },
	{ "FireWallMissileWormThink",			(byte*)FireWallMissileWormThink },

	// Message handlers.
	{ "DefaultMsgHandler",					(byte*)DefaultMsgHandler },
	{ "DyingMsgHandler",					(byte*)DyingMsgHandler },
	{ "DeadMsgHandler",						(byte*)DeadMsgHandler },

	// Terminator field.
	{ NULL, NULL }
};

#pragma endregion

#pragma region ================================ MMOVES LIST ================================

const animmove_map_t mmoves_list[] =
{
	// c_corvus1_anim.c:
	{ "corvus_move_c_action1",					&corvus_move_c_action1 },
	{ "corvus_move_c_action2",					&corvus_move_c_action2 },
	{ "corvus_move_c_action3",					&corvus_move_c_action3 },
	{ "corvus_move_c_action4",					&corvus_move_c_action4 },
	{ "corvus_move_c_idle1",					&corvus_move_c_idle1 },
	{ "corvus_move_c_idle2",					&corvus_move_c_idle2 },
	{ "corvus_move_c_pivotleft",				&corvus_move_c_pivotleft },
	{ "corvus_move_c_pivotleftgo",				&corvus_move_c_pivotleftgo },
	{ "corvus_move_c_pivotleftstop",			&corvus_move_c_pivotleftstop },
	{ "corvus_move_c_pivotright",				&corvus_move_c_pivotright },
	{ "corvus_move_c_pivotrightgo",				&corvus_move_c_pivotrightgo },
	{ "corvus_move_c_pivotrightstop",			&corvus_move_c_pivotrightstop },
	{ "corvus_move_c_strafeleft",				&corvus_move_c_strafeleft },
	{ "corvus_move_c_straferight",				&corvus_move_c_straferight },
	{ "corvus_move_c_walk1",					&corvus_move_c_walk1 },
	{ "corvus_move_c_walk2",					&corvus_move_c_walk2 },
	{ "corvus_move_c_walkstart",				&corvus_move_c_walkstart },
	{ "corvus_move_c_walkstop1",				&corvus_move_c_walkstop1 },
	{ "corvus_move_c_walkstop2",				&corvus_move_c_walkstop2 },

	// c_corvus2_anim.c:
	{ "corvus2_move_c_action1",					&corvus2_move_c_action1 },
	{ "corvus2_move_c_idle1",					&corvus2_move_c_idle1 },
	{ "corvus2_move_c_idle2",					&corvus2_move_c_idle2 },
	{ "corvus2_move_c_idle3",					&corvus2_move_c_idle3 },
	{ "corvus2_move_c_pivotleft",				&corvus2_move_c_pivotleft },
	{ "corvus2_move_c_pivotleftgo",				&corvus2_move_c_pivotleftgo },
	{ "corvus2_move_c_pivotleftstop",			&corvus2_move_c_pivotleftstop },
	{ "corvus2_move_c_pivotright",				&corvus2_move_c_pivotright },
	{ "corvus2_move_c_pivotrightgo",			&corvus2_move_c_pivotrightgo },
	{ "corvus2_move_c_pivotrightstop",			&corvus2_move_c_pivotrightstop },
	{ "corvus2_move_c_walk1",					&corvus2_move_c_walk1 },
	{ "corvus2_move_c_walk2",					&corvus2_move_c_walk2 },
	{ "corvus2_move_c_walkstart",				&corvus2_move_c_walkstart },
	{ "corvus2_move_c_walkstop1",				&corvus2_move_c_walkstop1 },
	{ "corvus2_move_c_walkstop2",				&corvus2_move_c_walkstop2 },

	// c_corvus3_anim.c:
	{ "corvus3_move_c_action1",					&corvus3_move_c_action1 },
	{ "corvus3_move_c_action10",				&corvus3_move_c_action10 },
	{ "corvus3_move_c_action11",				&corvus3_move_c_action11 },
	{ "corvus3_move_c_action12",				&corvus3_move_c_action12 },
	{ "corvus3_move_c_action13",				&corvus3_move_c_action13 },
	{ "corvus3_move_c_action14",				&corvus3_move_c_action14 },
	{ "corvus3_move_c_action15",				&corvus3_move_c_action15 },
	{ "corvus3_move_c_action16",				&corvus3_move_c_action16 },
	{ "corvus3_move_c_action17",				&corvus3_move_c_action17 },
	{ "corvus3_move_c_action18",				&corvus3_move_c_action18 },
	{ "corvus3_move_c_action19",				&corvus3_move_c_action19 },
	{ "corvus3_move_c_action2",					&corvus3_move_c_action2 },
	{ "corvus3_move_c_action20",				&corvus3_move_c_action20 },
	{ "corvus3_move_c_action3",					&corvus3_move_c_action3 },
	{ "corvus3_move_c_action4",					&corvus3_move_c_action4 },
	{ "corvus3_move_c_action5",					&corvus3_move_c_action5 },
	{ "corvus3_move_c_action6",					&corvus3_move_c_action6 },
	{ "corvus3_move_c_action7",					&corvus3_move_c_action7 },
	{ "corvus3_move_c_action8",					&corvus3_move_c_action8 },
	{ "corvus3_move_c_action9",					&corvus3_move_c_action9 },
	{ "corvus3_move_c_idle1",					&corvus3_move_c_idle1 },
	{ "corvus3_move_c_idle2",					&corvus3_move_c_idle2 },
	{ "corvus3_move_c_idle3",					&corvus3_move_c_idle3 },
	{ "corvus3_move_c_pivotleft",				&corvus3_move_c_pivotleft },
	{ "corvus3_move_c_pivotleftgo",				&corvus3_move_c_pivotleftgo },
	{ "corvus3_move_c_pivotleftstop",			&corvus3_move_c_pivotleftstop },
	{ "corvus3_move_c_pivotright",				&corvus3_move_c_pivotright },
	{ "corvus3_move_c_pivotrightgo",			&corvus3_move_c_pivotrightgo },
	{ "corvus3_move_c_pivotrightstop",			&corvus3_move_c_pivotrightstop },
	{ "corvus3_move_c_walk1",					&corvus3_move_c_walk1 },
	{ "corvus3_move_c_walk2",					&corvus3_move_c_walk2 },
	{ "corvus3_move_c_walk3",					&corvus3_move_c_walk3 },
	{ "corvus3_move_c_walkstart",				&corvus3_move_c_walkstart },
	{ "corvus3_move_c_walkstop1",				&corvus3_move_c_walkstop1 },
	{ "corvus3_move_c_walkstop2",				&corvus3_move_c_walkstop2 },

	// c_corvus4_anim.c:
	{ "corvus4_move_c_action1",					&corvus4_move_c_action1 },
	{ "corvus4_move_c_action2",					&corvus4_move_c_action2 },
	{ "corvus4_move_c_action3",					&corvus4_move_c_action3 },
	{ "corvus4_move_c_action4",					&corvus4_move_c_action4 },
	{ "corvus4_move_c_action5",					&corvus4_move_c_action5 },
	{ "corvus4_move_c_idle1",					&corvus4_move_c_idle1 },
	{ "corvus4_move_c_idle2",					&corvus4_move_c_idle2 },
	{ "corvus4_move_c_pivotleft",				&corvus4_move_c_pivotleft },
	{ "corvus4_move_c_pivotleftgo",				&corvus4_move_c_pivotleftgo },
	{ "corvus4_move_c_pivotleftstop",			&corvus4_move_c_pivotleftstop },
	{ "corvus4_move_c_pivotright",				&corvus4_move_c_pivotright },
	{ "corvus4_move_c_pivotrightgo",			&corvus4_move_c_pivotrightgo },
	{ "corvus4_move_c_pivotrightstop",			&corvus4_move_c_pivotrightstop },
	{ "corvus4_move_c_walk1",					&corvus4_move_c_walk1 },
	{ "corvus4_move_c_walk2",					&corvus4_move_c_walk2 },
	{ "corvus4_move_c_walkstart",				&corvus4_move_c_walkstart },
	{ "corvus4_move_c_walkstop1",				&corvus4_move_c_walkstop1 },
	{ "corvus4_move_c_walkstop2",				&corvus4_move_c_walkstop2 },

	// c_corvus5_anim.c:
	{ "corvus5_move_c_action1",					&corvus5_move_c_action1 },
	{ "corvus5_move_c_action2",					&corvus5_move_c_action2 },
	{ "corvus5_move_c_action3",					&corvus5_move_c_action3 },
	{ "corvus5_move_c_action4",					&corvus5_move_c_action4 },
	{ "corvus5_move_c_action5",					&corvus5_move_c_action5 },
	{ "corvus5_move_c_action6",					&corvus5_move_c_action6 },
	{ "corvus5_move_c_action7",					&corvus5_move_c_action7 },
	{ "corvus5_move_c_action8",					&corvus5_move_c_action8 },
	{ "corvus5_move_c_idle1",					&corvus5_move_c_idle1 },
	{ "corvus5_move_c_idle2",					&corvus5_move_c_idle2 },
	{ "corvus5_move_c_idle3",					&corvus5_move_c_idle3 },
	{ "corvus5_move_c_pivotleft",				&corvus5_move_c_pivotleft },
	{ "corvus5_move_c_pivotleftgo",				&corvus5_move_c_pivotleftgo },
	{ "corvus5_move_c_pivotleftstop",			&corvus5_move_c_pivotleftstop },
	{ "corvus5_move_c_pivotright",				&corvus5_move_c_pivotright },
	{ "corvus5_move_c_pivotrightgo",			&corvus5_move_c_pivotrightgo },
	{ "corvus5_move_c_pivotrightstop",			&corvus5_move_c_pivotrightstop },
	{ "corvus5_move_c_walk1",					&corvus5_move_c_walk1 },
	{ "corvus5_move_c_walk2",					&corvus5_move_c_walk2 },
	{ "corvus5_move_c_walkstart",				&corvus5_move_c_walkstart },
	{ "corvus5_move_c_walkstop1",				&corvus5_move_c_walkstop1 },
	{ "corvus5_move_c_walkstop2",				&corvus5_move_c_walkstop2 },

	// c_corvus6_anim.c:
	{ "corvus6_move_c_action1",					&corvus6_move_c_action1 },
	{ "corvus6_move_c_action10",				&corvus6_move_c_action10 },
	{ "corvus6_move_c_action11",				&corvus6_move_c_action11 },
	{ "corvus6_move_c_action2",					&corvus6_move_c_action2 },
	{ "corvus6_move_c_action3",					&corvus6_move_c_action3 },
	{ "corvus6_move_c_action4",					&corvus6_move_c_action4 },
	{ "corvus6_move_c_action5",					&corvus6_move_c_action5 },
	{ "corvus6_move_c_action6",					&corvus6_move_c_action6 },
	{ "corvus6_move_c_action7",					&corvus6_move_c_action7 },
	{ "corvus6_move_c_action8",					&corvus6_move_c_action8 },
	{ "corvus6_move_c_action9",					&corvus6_move_c_action9 },
	{ "corvus6_move_c_idle1",					&corvus6_move_c_idle1 },
	{ "corvus6_move_c_idle2",					&corvus6_move_c_idle2 },
	{ "corvus6_move_c_idle3",					&corvus6_move_c_idle3 },
	{ "corvus6_move_c_idle4",					&corvus6_move_c_idle4 },
	{ "corvus6_move_c_idle5",					&corvus6_move_c_idle5 },

	// c_corvus7_anim.c:
	{ "corvus7_move_c_action1",					&corvus7_move_c_action1 },
	{ "corvus7_move_c_action2",					&corvus7_move_c_action2 },
	{ "corvus7_move_c_action3",					&corvus7_move_c_action3 },
	{ "corvus7_move_c_idle1",					&corvus7_move_c_idle1 },
	{ "corvus7_move_c_idle2",					&corvus7_move_c_idle2 },
	{ "corvus7_move_c_idle3",					&corvus7_move_c_idle3 },
	{ "corvus7_move_c_pivotleft",				&corvus7_move_c_pivotleft },
	{ "corvus7_move_c_pivotleftgo",				&corvus7_move_c_pivotleftgo },
	{ "corvus7_move_c_pivotleftstop",			&corvus7_move_c_pivotleftstop },
	{ "corvus7_move_c_pivotright",				&corvus7_move_c_pivotright },
	{ "corvus7_move_c_pivotrightgo",			&corvus7_move_c_pivotrightgo },
	{ "corvus7_move_c_pivotrightstop",			&corvus7_move_c_pivotrightstop },
	{ "corvus7_move_c_walk1",					&corvus7_move_c_walk1 },
	{ "corvus7_move_c_walk2",					&corvus7_move_c_walk2 },
	{ "corvus7_move_c_walkstart",				&corvus7_move_c_walkstart },
	{ "corvus7_move_c_walkstop1",				&corvus7_move_c_walkstop1 },
	{ "corvus7_move_c_walkstop2",				&corvus7_move_c_walkstop2 },

	// c_corvus8_anim.c:
	{ "corvus8_move_c_action1",					&corvus8_move_c_action1 },
	{ "corvus8_move_c_action10",				&corvus8_move_c_action10 },
	{ "corvus8_move_c_action11",				&corvus8_move_c_action11 },
	{ "corvus8_move_c_action12",				&corvus8_move_c_action12 },
	{ "corvus8_move_c_action13",				&corvus8_move_c_action13 },
	{ "corvus8_move_c_action14",				&corvus8_move_c_action14 },
	{ "corvus8_move_c_action15",				&corvus8_move_c_action15 },
	{ "corvus8_move_c_action16",				&corvus8_move_c_action16 },
	{ "corvus8_move_c_action17",				&corvus8_move_c_action17 },
	{ "corvus8_move_c_action18",				&corvus8_move_c_action18 },
	{ "corvus8_move_c_action19",				&corvus8_move_c_action19 },
	{ "corvus8_move_c_action2",					&corvus8_move_c_action2 },
	{ "corvus8_move_c_action20",				&corvus8_move_c_action20 },
	{ "corvus8_move_c_action3",					&corvus8_move_c_action3 },
	{ "corvus8_move_c_action4",					&corvus8_move_c_action4 },
	{ "corvus8_move_c_action5",					&corvus8_move_c_action5 },
	{ "corvus8_move_c_action6",					&corvus8_move_c_action6 },
	{ "corvus8_move_c_action7",					&corvus8_move_c_action7 },
	{ "corvus8_move_c_action8",					&corvus8_move_c_action8 },
	{ "corvus8_move_c_action9",					&corvus8_move_c_action9 },
	{ "corvus8_move_c_idle1",					&corvus8_move_c_idle1 },
	{ "corvus8_move_c_idle2",					&corvus8_move_c_idle2 },
	{ "corvus8_move_c_pivotleft",				&corvus8_move_c_pivotleft },
	{ "corvus8_move_c_pivotleftgo",				&corvus8_move_c_pivotleftgo },
	{ "corvus8_move_c_pivotleftstop",			&corvus8_move_c_pivotleftstop },
	{ "corvus8_move_c_pivotright",				&corvus8_move_c_pivotright },
	{ "corvus8_move_c_pivotrightgo",			&corvus8_move_c_pivotrightgo },
	{ "corvus8_move_c_pivotrightstop",			&corvus8_move_c_pivotrightstop },
	{ "corvus8_move_c_walk1",					&corvus8_move_c_walk1 },
	{ "corvus8_move_c_walk2",					&corvus8_move_c_walk2 },
	{ "corvus8_move_c_walk3",					&corvus8_move_c_walk3 },
	{ "corvus8_move_c_walkstart",				&corvus8_move_c_walkstart },
	{ "corvus8_move_c_walkstop1",				&corvus8_move_c_walkstop1 },
	{ "corvus8_move_c_walkstop2",				&corvus8_move_c_walkstop2 },

	// c_corvus9_anim.c:
	{ "corvus9_move_c_action1",					&corvus9_move_c_action1 },
	{ "corvus9_move_c_action10",				&corvus9_move_c_action10 },
	{ "corvus9_move_c_action11",				&corvus9_move_c_action11 },
	{ "corvus9_move_c_action2",					&corvus9_move_c_action2 },
	{ "corvus9_move_c_action3",					&corvus9_move_c_action3 },
	{ "corvus9_move_c_action4",					&corvus9_move_c_action4 },
	{ "corvus9_move_c_action5",					&corvus9_move_c_action5 },
	{ "corvus9_move_c_action6",					&corvus9_move_c_action6 },
	{ "corvus9_move_c_action7",					&corvus9_move_c_action7 },
	{ "corvus9_move_c_action8",					&corvus9_move_c_action8 },
	{ "corvus9_move_c_action9",					&corvus9_move_c_action9 },
	{ "corvus9_move_c_idle1",					&corvus9_move_c_idle1 },
	{ "corvus9_move_c_idle2",					&corvus9_move_c_idle2 },
	{ "corvus9_move_c_idle3",					&corvus9_move_c_idle3 },
	{ "corvus9_move_c_walk1",					&corvus9_move_c_walk1 },
	{ "corvus9_move_c_walk2",					&corvus9_move_c_walk2 },

	// c_dranor_anim.c:
	{ "dranor_move_c_action1",					&dranor_move_c_action1 },
	{ "dranor_move_c_action10",					&dranor_move_c_action10 },
	{ "dranor_move_c_action11",					&dranor_move_c_action11 },
	{ "dranor_move_c_action12",					&dranor_move_c_action12 },
	{ "dranor_move_c_action2",					&dranor_move_c_action2 },
	{ "dranor_move_c_action3",					&dranor_move_c_action3 },
	{ "dranor_move_c_action4",					&dranor_move_c_action4 },
	{ "dranor_move_c_action5",					&dranor_move_c_action5 },
	{ "dranor_move_c_action6",					&dranor_move_c_action6 },
	{ "dranor_move_c_action7",					&dranor_move_c_action7 },
	{ "dranor_move_c_action8",					&dranor_move_c_action8 },
	{ "dranor_move_c_action9",					&dranor_move_c_action9 },
	{ "dranor_move_c_death1",					&dranor_move_c_death1 },
	{ "dranor_move_c_idle1",					&dranor_move_c_idle1 },
	{ "dranor_move_c_idle2",					&dranor_move_c_idle2 },
	{ "dranor_move_c_idle3",					&dranor_move_c_idle3 },

	// c_elflord_anim.c:
	{ "elflord_move_c_action1",					&elflord_move_c_action1 },
	{ "elflord_move_c_action2",					&elflord_move_c_action2 },
	{ "elflord_move_c_death1",					&elflord_move_c_death1 },
	{ "elflord_move_c_death2",					&elflord_move_c_death2 },
	{ "elflord_move_c_idle1",					&elflord_move_c_idle1 },
	{ "elflord_move_c_idle2",					&elflord_move_c_idle2 },

	// c_morcalavin_anim.c:
	{ "morcalavin_move_c_action1",				&morcalavin_move_c_action1 },
	{ "morcalavin_move_c_action2",				&morcalavin_move_c_action2 },
	{ "morcalavin_move_c_action3",				&morcalavin_move_c_action3 },
	{ "morcalavin_move_c_idle1",				&morcalavin_move_c_idle1 },
	{ "morcalavin_move_c_idle2",				&morcalavin_move_c_idle2 },
	{ "morcalavin_move_c_idle3",				&morcalavin_move_c_idle3 },
	{ "morcalavin_move_c_idle4",				&morcalavin_move_c_idle4 },

	// c_priestess2_anim.c:
	{ "priestess2_move_c_action1",				&priestess2_move_c_action1 },
	{ "priestess2_move_c_action2",				&priestess2_move_c_action2 },
	{ "priestess2_move_c_action3",				&priestess2_move_c_action3 },
	{ "priestess2_move_c_action4",				&priestess2_move_c_action4 },
	{ "priestess2_move_c_action5",				&priestess2_move_c_action5 },
	{ "priestess2_move_c_action6",				&priestess2_move_c_action6 },
	{ "priestess2_move_c_action7",				&priestess2_move_c_action7 },
	{ "priestess2_move_c_idle1",				&priestess2_move_c_idle1 },

	// c_priestess_anim.c:
	{ "priestess_move_c_action1",				&priestess_move_c_action1 },
	{ "priestess_move_c_action10",				&priestess_move_c_action10 },
	{ "priestess_move_c_action11",				&priestess_move_c_action11 },
	{ "priestess_move_c_action12",				&priestess_move_c_action12 },
	{ "priestess_move_c_action13",				&priestess_move_c_action13 },
	{ "priestess_move_c_action14",				&priestess_move_c_action14 },
	{ "priestess_move_c_action15",				&priestess_move_c_action15 },
	{ "priestess_move_c_action16",				&priestess_move_c_action16 },
	{ "priestess_move_c_action2",				&priestess_move_c_action2 },
	{ "priestess_move_c_action3",				&priestess_move_c_action3 },
	{ "priestess_move_c_action4",				&priestess_move_c_action4 },
	{ "priestess_move_c_action5",				&priestess_move_c_action5 },
	{ "priestess_move_c_action6",				&priestess_move_c_action6 },
	{ "priestess_move_c_action7",				&priestess_move_c_action7 },
	{ "priestess_move_c_action8",				&priestess_move_c_action8 },
	{ "priestess_move_c_action9",				&priestess_move_c_action9 },
	{ "priestess_move_c_backpedal1",			&priestess_move_c_backpedal1 },
	{ "priestess_move_c_idle1",					&priestess_move_c_idle1 },
	{ "priestess_move_c_idle2",					&priestess_move_c_idle2 },
	{ "priestess_move_c_walk1",					&priestess_move_c_walk1 },

	// c_siernan1_anim.c:
	{ "siernan1_move_c_action1",				&siernan1_move_c_action1 },
	{ "siernan1_move_c_action10",				&siernan1_move_c_action10 },
	{ "siernan1_move_c_action11",				&siernan1_move_c_action11 },
	{ "siernan1_move_c_action12",				&siernan1_move_c_action12 },
	{ "siernan1_move_c_action13",				&siernan1_move_c_action13 },
	{ "siernan1_move_c_action2",				&siernan1_move_c_action2 },
	{ "siernan1_move_c_action3",				&siernan1_move_c_action3 },
	{ "siernan1_move_c_action4",				&siernan1_move_c_action4 },
	{ "siernan1_move_c_action5",				&siernan1_move_c_action5 },
	{ "siernan1_move_c_action6",				&siernan1_move_c_action6 },
	{ "siernan1_move_c_action7",				&siernan1_move_c_action7 },
	{ "siernan1_move_c_action8",				&siernan1_move_c_action8 },
	{ "siernan1_move_c_action9",				&siernan1_move_c_action9 },
	{ "siernan1_move_c_idle1",					&siernan1_move_c_idle1 },
	{ "siernan1_move_c_idle2",					&siernan1_move_c_idle2 },
	{ "siernan1_move_c_idle3",					&siernan1_move_c_idle3 },
	{ "siernan1_move_c_idle4",					&siernan1_move_c_idle4 },
	{ "siernan1_move_c_idle5",					&siernan1_move_c_idle5 },
	{ "siernan1_move_c_walk1",					&siernan1_move_c_walk1 },
	{ "siernan1_move_c_walkstart",				&siernan1_move_c_walkstart },
	{ "siernan1_move_c_walkstop1",				&siernan1_move_c_walkstop1 },

	// c_siernan2_anim.c:
	{ "siernan2_move_c_action1",				&siernan2_move_c_action1 },
	{ "siernan2_move_c_action2",				&siernan2_move_c_action2 },
	{ "siernan2_move_c_idle1",					&siernan2_move_c_idle1 },

	// c_ssithrascout_anim.c:
	{ "scout_move_c_action1",					&scout_move_c_action1 },
	{ "scout_move_c_action10",					&scout_move_c_action10 },
	{ "scout_move_c_action2",					&scout_move_c_action2 },
	{ "scout_move_c_action3",					&scout_move_c_action3 },
	{ "scout_move_c_action4",					&scout_move_c_action4 },
	{ "scout_move_c_action5",					&scout_move_c_action5 },
	{ "scout_move_c_action6",					&scout_move_c_action6 },
	{ "scout_move_c_action7",					&scout_move_c_action7 },
	{ "scout_move_c_action8",					&scout_move_c_action8 },
	{ "scout_move_c_action9",					&scout_move_c_action9 },
	{ "scout_move_c_death1",					&scout_move_c_death1 },
	{ "scout_move_c_idle1",						&scout_move_c_idle1 },
	{ "scout_move_c_idle2",						&scout_move_c_idle2 },
	{ "scout_move_c_idle3",						&scout_move_c_idle3 },

	// c_tome_anim.c:
	{ "tome_move_c_idle1",						&tome_move_c_idle1 },
	{ "tome_move_c_idle2",						&tome_move_c_idle2 },

	// c_victimSsithra_anim.c:
	{ "victimSsithra_move_c_action1",			&victimSsithra_move_c_action1 },
	{ "victimSsithra_move_c_action2",			&victimSsithra_move_c_action2 },
	{ "victimSsithra_move_c_action3",			&victimSsithra_move_c_action3 },
	{ "victimSsithra_move_c_action4",			&victimSsithra_move_c_action4 },
	{ "victimSsithra_move_c_action5",			&victimSsithra_move_c_action5 },
	{ "victimSsithra_move_c_action6",			&victimSsithra_move_c_action6 },

	// m_assassin_anim.c:
	{ "assassin_move_backflip",					&assassin_move_backflip },
	{ "assassin_move_backspring",				&assassin_move_backspring },
	{ "assassin_move_bfinair",					&assassin_move_bfinair },
	{ "assassin_move_bfland",					&assassin_move_bfland },
	{ "assassin_move_c_attack1",				&assassin_move_c_attack1 },
	{ "assassin_move_c_attack2",				&assassin_move_c_attack2 },
	{ "assassin_move_c_idle1",					&assassin_move_c_idle1 },
	{ "assassin_move_c_run1",					&assassin_move_c_run1 },
	{ "assassin_move_cloak",					&assassin_move_cloak },
	{ "assassin_move_crouch",					&assassin_move_crouch },
	{ "assassin_move_crouch_end",				&assassin_move_crouch_end },
	{ "assassin_move_crouch_idle",				&assassin_move_crouch_idle },
	{ "assassin_move_crouch_look_l2c",			&assassin_move_crouch_look_l2c },
	{ "assassin_move_crouch_look_l2r",			&assassin_move_crouch_look_l2r },
	{ "assassin_move_crouch_look_left",			&assassin_move_crouch_look_left },
	{ "assassin_move_crouch_look_left_idle",	&assassin_move_crouch_look_left_idle },
	{ "assassin_move_crouch_look_r2c",			&assassin_move_crouch_look_r2c },
	{ "assassin_move_crouch_look_r2l",			&assassin_move_crouch_look_r2l },
	{ "assassin_move_crouch_look_right",		&assassin_move_crouch_look_right },
	{ "assassin_move_crouch_look_right_idle",	&assassin_move_crouch_look_right_idle },
	{ "assassin_move_crouch_poke",				&assassin_move_crouch_poke },
	{ "assassin_move_crouch_trans",				&assassin_move_crouch_trans },
	{ "assassin_move_daggerb",					&assassin_move_daggerb },
	{ "assassin_move_daggerc",					&assassin_move_daggerc },
	{ "assassin_move_daggerl",					&assassin_move_daggerl },
	{ "assassin_move_daggerr",					&assassin_move_daggerr },
	{ "assassin_move_deatha",					&assassin_move_deatha },
	{ "assassin_move_deathb",					&assassin_move_deathb },
	{ "assassin_move_delay",					&assassin_move_delay },
	{ "assassin_move_dodge_left",				&assassin_move_dodge_left },
	{ "assassin_move_dodge_right",				&assassin_move_dodge_right },
	{ "assassin_move_evade_backflip",			&assassin_move_evade_backflip },
	{ "assassin_move_evade_frontflip",			&assassin_move_evade_frontflip },
	{ "assassin_move_evade_jump",				&assassin_move_evade_jump },
	{ "assassin_move_evinair",					&assassin_move_evinair },
	{ "assassin_move_ffinair",					&assassin_move_ffinair },
	{ "assassin_move_ffland",					&assassin_move_ffland },
	{ "assassin_move_fjump",					&assassin_move_fjump },
	{ "assassin_move_forcedjump",				&assassin_move_forcedjump },
	{ "assassin_move_frontflip",				&assassin_move_frontflip },
	{ "assassin_move_inair",					&assassin_move_inair },
	{ "assassin_move_jump",						&assassin_move_jump },
	{ "assassin_move_land",						&assassin_move_land },
	{ "assassin_move_newdagger",				&assassin_move_newdagger },
	{ "assassin_move_newdaggerb",				&assassin_move_newdaggerb },
	{ "assassin_move_pain1",					&assassin_move_pain1 },
	{ "assassin_move_pain2",					&assassin_move_pain2 },
	{ "assassin_move_run",						&assassin_move_run },
	{ "assassin_move_stand",					&assassin_move_stand },
	{ "assassin_move_teleport",					&assassin_move_teleport },
	{ "assassin_move_uncrouch",					&assassin_move_uncrouch },
	{ "assassin_move_walk",						&assassin_move_walk },
	{ "assassin_move_walk_loop",				&assassin_move_walk_loop },

	// m_beast_anim.c:
	{ "tbeast_move_bitelow",					&tbeast_move_bitelow },
	{ "tbeast_move_bitelow_sfin",				&tbeast_move_bitelow_sfin },
	{ "tbeast_move_biteup",						&tbeast_move_biteup },
	{ "tbeast_move_biteup_sfin",				&tbeast_move_biteup_sfin },
	{ "tbeast_move_biteup2",					&tbeast_move_biteup2 },
	{ "tbeast_move_biteup2_sfin",				&tbeast_move_biteup2_sfin },
	{ "tbeast_move_catch",						&tbeast_move_catch },
	{ "tbeast_move_charge",						&tbeast_move_charge },
	{ "tbeast_move_delay",						&tbeast_move_delay },
	{ "tbeast_move_die",						&tbeast_move_die },
	{ "tbeast_move_die_norm",					&tbeast_move_die_norm },
	{ "tbeast_move_eatdown",					&tbeast_move_eatdown },
	{ "tbeast_move_eating",						&tbeast_move_eating },
	{ "tbeast_move_eating_twitch",				&tbeast_move_eating_twitch },
	{ "tbeast_move_forced_jump",				&tbeast_move_forced_jump },
	{ "tbeast_move_ginair",						&tbeast_move_ginair },
	{ "tbeast_move_gland",						&tbeast_move_gland },
	{ "tbeast_move_inair",						&tbeast_move_inair },
	{ "tbeast_move_jump",						&tbeast_move_jump },
	{ "tbeast_move_land",						&tbeast_move_land },
	{ "tbeast_move_quick_charge",				&tbeast_move_quick_charge },
	{ "tbeast_move_ready_catch",				&tbeast_move_ready_catch },
	{ "tbeast_move_roar",						&tbeast_move_roar },
	{ "tbeast_move_snatch",						&tbeast_move_snatch },
	{ "tbeast_move_stand",						&tbeast_move_stand },
	{ "tbeast_move_stun",						&tbeast_move_stun },
	{ "tbeast_move_walk",						&tbeast_move_walk },
	{ "tbeast_move_walkatk",					&tbeast_move_walkatk },
	{ "tbeast_move_walkleft",					&tbeast_move_walkleft },
	{ "tbeast_move_walkrt",						&tbeast_move_walkrt },

	// m_chicken_anim.c:
	{ "chicken_move_attack",					&chicken_move_attack },
	{ "chicken_move_cluck",						&chicken_move_cluck },
	{ "chicken_move_eat",						&chicken_move_eat },
	{ "chicken_move_jump",						&chicken_move_jump },
	{ "chicken_move_run",						&chicken_move_run },
	{ "chicken_move_stand1",					&chicken_move_stand1 },
	{ "chicken_move_walk",						&chicken_move_walk },

	// m_elflord_anim.c:
	{ "elflord_move_attack",					&elflord_move_attack },
	{ "elflord_move_charge",					&elflord_move_charge },
	{ "elflord_move_charge_trans",				&elflord_move_charge_trans },
	{ "elflord_move_come_to_life",				&elflord_move_come_to_life },
	{ "elflord_move_death_btrans",				&elflord_move_death_btrans },
	{ "elflord_move_death_loop",				&elflord_move_death_loop },
	{ "elflord_move_dodgeleft",					&elflord_move_dodgeleft },
	{ "elflord_move_dodgeright",				&elflord_move_dodgeright },
	{ "elflord_move_floatback",					&elflord_move_floatback },
	{ "elflord_move_idle",						&elflord_move_idle },
	{ "elflord_move_ls",						&elflord_move_ls },
	{ "elflord_move_move",						&elflord_move_move },
	{ "elflord_move_pain",						&elflord_move_pain },
	{ "elflord_move_run",						&elflord_move_run },
	{ "elflord_move_shield",					&elflord_move_shield },
	{ "elflord_move_soa_begin",					&elflord_move_soa_begin },
	{ "elflord_move_soa_end",					&elflord_move_soa_end },
	{ "elflord_move_soa_loop",					&elflord_move_soa_loop },
	{ "elflord_move_wait",						&elflord_move_wait },

	// m_fish_anim.c:
	{ "fish_move_bite",							&fish_move_bite },
	{ "fish_move_death",						&fish_move_death },
	{ "fish_move_melee",						&fish_move_melee },
	{ "fish_move_pain1",						&fish_move_pain1 },
	{ "fish_move_run1",							&fish_move_run1 },
	{ "fish_move_run2",							&fish_move_run2 },
	{ "fish_move_run3",							&fish_move_run3 },
	{ "fish_move_stand1",						&fish_move_stand1 },
	{ "fish_move_walk1",						&fish_move_walk1 },
	{ "fish_move_walk2",						&fish_move_walk2 },
	{ "fish_move_walk3",						&fish_move_walk3 },

	// m_gkrokon_anim.c:
	{ "gkrokon_move_crouch1",					&gkrokon_move_crouch1 },
	{ "gkrokon_move_crouch2",					&gkrokon_move_crouch2 },
	{ "gkrokon_move_crouch3",					&gkrokon_move_crouch3 },
	{ "gkrokon_move_death1",					&gkrokon_move_death1 },
	{ "gkrokon_move_delay",						&gkrokon_move_delay },
	{ "gkrokon_move_eat1",						&gkrokon_move_eat1 },
	{ "gkrokon_move_eat2",						&gkrokon_move_eat2 },
	{ "gkrokon_move_eat3",						&gkrokon_move_eat3 },
	{ "gkrokon_move_forced_jump",				&gkrokon_move_forced_jump },
	{ "gkrokon_move_hop1",						&gkrokon_move_hop1 },
	{ "gkrokon_move_jump1",						&gkrokon_move_jump1 },
	{ "gkrokon_move_melee_attack1",				&gkrokon_move_melee_attack1 },
	{ "gkrokon_move_melee_attack2",				&gkrokon_move_melee_attack2 },
	{ "gkrokon_move_missile_attack1",			&gkrokon_move_missile_attack1 },
	{ "gkrokon_move_missile_attack2",			&gkrokon_move_missile_attack2 },
	{ "gkrokon_move_pain1",						&gkrokon_move_pain1 },
	{ "gkrokon_move_run_away",					&gkrokon_move_run_away },
	{ "gkrokon_move_run1",						&gkrokon_move_run1 },
	{ "gkrokon_move_run2",						&gkrokon_move_run2 },
	{ "gkrokon_move_stand1",					&gkrokon_move_stand1 },
	{ "gkrokon_move_stand2",					&gkrokon_move_stand2 },
	{ "gkrokon_move_stand3",					&gkrokon_move_stand3 },
	{ "gkrokon_move_stand4",					&gkrokon_move_stand4 },
	{ "gkrokon_move_walk1",						&gkrokon_move_walk1 },

	// m_gorgon_anim.c:
	{ "gorgon_move_catch",						&gorgon_move_catch },
	{ "gorgon_move_death2slide",				&gorgon_move_death2slide },
	{ "gorgon_move_death2twitch",				&gorgon_move_death2twitch },
	{ "gorgon_move_delay",						&gorgon_move_delay },
	{ "gorgon_move_die1",						&gorgon_move_die1 },
	{ "gorgon_move_die2",						&gorgon_move_die2 },
	{ "gorgon_move_eat_down",					&gorgon_move_eat_down },
	{ "gorgon_move_eat_left",					&gorgon_move_eat_left },
	{ "gorgon_move_eat_loop",					&gorgon_move_eat_loop },
	{ "gorgon_move_eat_pullback",				&gorgon_move_eat_pullback },
	{ "gorgon_move_eat_react",					&gorgon_move_eat_react },
	{ "gorgon_move_eat_right",					&gorgon_move_eat_right },
	{ "gorgon_move_eat_snap",					&gorgon_move_eat_snap },
	{ "gorgon_move_eat_tear",					&gorgon_move_eat_tear },
	{ "gorgon_move_eat_up",						&gorgon_move_eat_up },
	{ "gorgon_move_fjump",						&gorgon_move_fjump },
	{ "gorgon_move_inair",						&gorgon_move_inair },
	{ "gorgon_move_land",						&gorgon_move_land },
	{ "gorgon_move_land2",						&gorgon_move_land2 },
	{ "gorgon_move_look_around",				&gorgon_move_look_around },
	{ "gorgon_move_melee1",						&gorgon_move_melee1 },
	{ "gorgon_move_melee10",					&gorgon_move_melee10 },
	{ "gorgon_move_melee2",						&gorgon_move_melee2 },
	{ "gorgon_move_melee3",						&gorgon_move_melee3 },
	{ "gorgon_move_melee4",						&gorgon_move_melee4 },
	{ "gorgon_move_melee5",						&gorgon_move_melee5 },
	{ "gorgon_move_melee6",						&gorgon_move_melee6 },
	{ "gorgon_move_melee7",						&gorgon_move_melee7 },
	{ "gorgon_move_melee8",						&gorgon_move_melee8 },
	{ "gorgon_move_melee9",						&gorgon_move_melee9 },
	{ "gorgon_move_miss",						&gorgon_move_miss },
	{ "gorgon_move_outwater",					&gorgon_move_outwater },
	{ "gorgon_move_pain1",						&gorgon_move_pain1 },
	{ "gorgon_move_pain2",						&gorgon_move_pain2 },
	{ "gorgon_move_pain3",						&gorgon_move_pain3 },
	{ "gorgon_move_readycatch",					&gorgon_move_readycatch },
	{ "gorgon_move_roar",						&gorgon_move_roar },
	{ "gorgon_move_roar2",						&gorgon_move_roar2 },
	{ "gorgon_move_run1",						&gorgon_move_run1 },
	{ "gorgon_move_run2",						&gorgon_move_run2 },
	{ "gorgon_move_run3",						&gorgon_move_run3 },
	{ "gorgon_move_slip",						&gorgon_move_slip },
	{ "gorgon_move_slip_pain",					&gorgon_move_slip_pain },
	{ "gorgon_move_snatch",						&gorgon_move_snatch },
	{ "gorgon_move_snatchhi",					&gorgon_move_snatchhi },
	{ "gorgon_move_snatchlow",					&gorgon_move_snatchlow },
	{ "gorgon_move_stand1",						&gorgon_move_stand1 },
	{ "gorgon_move_stand2",						&gorgon_move_stand2 },
	{ "gorgon_move_stand3",						&gorgon_move_stand3 },
	{ "gorgon_move_stand4",						&gorgon_move_stand4 },
	{ "gorgon_move_swim",						&gorgon_move_swim },
	{ "gorgon_move_swim_bite_a",				&gorgon_move_swim_bite_a },
	{ "gorgon_move_swim_bite_b",				&gorgon_move_swim_bite_b },
	{ "gorgon_move_to_swim",					&gorgon_move_to_swim },
	{ "gorgon_move_walk",						&gorgon_move_walk },
	{ "gorgon_move_walk2",						&gorgon_move_walk2 },
	{ "gorgon_move_walk3",						&gorgon_move_walk3 },

	// m_harpy_anim.c:
	{ "harpy_move_circle",						&harpy_move_circle },
	{ "harpy_move_circle_flap",					&harpy_move_circle_flap },
	{ "harpy_move_die1",						&harpy_move_die1 },
	{ "harpy_move_dive_end",					&harpy_move_dive_end },
	{ "harpy_move_dive_go",						&harpy_move_dive_go },
	{ "harpy_move_dive_hit_loop",				&harpy_move_dive_hit_loop },
	{ "harpy_move_dive_loop",					&harpy_move_dive_loop },
	{ "harpy_move_dive_trans",					&harpy_move_dive_trans },
	{ "harpy_move_fly1",						&harpy_move_fly1 },
	{ "harpy_move_flyback1",					&harpy_move_flyback1 },
	{ "harpy_move_hover1",						&harpy_move_hover1 },
	{ "harpy_move_hoverscream",					&harpy_move_hoverscream },
	{ "harpy_move_pain1",						&harpy_move_pain1 },
	{ "harpy_move_perch1_idle",					&harpy_move_perch1_idle },
	{ "harpy_move_perch2_idle",					&harpy_move_perch2_idle },
	{ "harpy_move_perch3_idle",					&harpy_move_perch3_idle },
	{ "harpy_move_perch4_idle",					&harpy_move_perch4_idle },
	{ "harpy_move_perch5_idle",					&harpy_move_perch5_idle },
	{ "harpy_move_perch6_idle",					&harpy_move_perch6_idle },
	{ "harpy_move_perch7_idle",					&harpy_move_perch7_idle },
	{ "harpy_move_perch8_idle",					&harpy_move_perch8_idle },
	{ "harpy_move_perch9_idle",					&harpy_move_perch9_idle },
	{ "harpy_move_takeoff",						&harpy_move_takeoff },
	{ "harpy_move_tumble",						&harpy_move_tumble },

	// m_imp_anim.c:
	{ "imp_move_ddown",							&imp_move_ddown },
	{ "imp_move_die1",							&imp_move_die1 },
	{ "imp_move_dive_end",						&imp_move_dive_end },
	{ "imp_move_dive_go",						&imp_move_dive_go },
	{ "imp_move_dive_loop",						&imp_move_dive_loop },
	{ "imp_move_dive_out",						&imp_move_dive_out },
	{ "imp_move_dup",							&imp_move_dup },
	{ "imp_move_fireball",						&imp_move_fireball },
	{ "imp_move_fly1",							&imp_move_fly1 },
	{ "imp_move_flyback",						&imp_move_flyback },
	{ "imp_move_hover1",						&imp_move_hover1 },
	{ "imp_move_pain1",							&imp_move_pain1 },
	{ "imp_move_perch",							&imp_move_perch },
	{ "imp_move_takeoff",						&imp_move_takeoff },
	{ "imp_move_tumble",						&imp_move_tumble },

	// m_morcalavin_anim.c:
	{ "morcalavin_move_attack1",				&morcalavin_move_attack1 },
	{ "morcalavin_move_attack2",				&morcalavin_move_attack2 },
	{ "morcalavin_move_attack2b",				&morcalavin_move_attack2b },
	{ "morcalavin_move_attack3",				&morcalavin_move_attack3 },
	{ "morcalavin_move_attack4",				&morcalavin_move_attack4 },
	{ "morcalavin_move_def1",					&morcalavin_move_def1 },
	{ "morcalavin_move_def2",					&morcalavin_move_def2 },
	{ "morcalavin_move_fall",					&morcalavin_move_fall },
	{ "morcalavin_move_float",					&morcalavin_move_float },
	{ "morcalavin_move_fly",					&morcalavin_move_fly },
	{ "morcalavin_move_getup",					&morcalavin_move_getup },
	{ "morcalavin_move_glide",					&morcalavin_move_glide },
	{ "morcalavin_move_ground_attack",			&morcalavin_move_ground_attack },
	{ "morcalavin_move_hurtidle",				&morcalavin_move_hurtidle },
	{ "morcalavin_move_retort",					&morcalavin_move_retort },
	{ "morcalavin_move_tracking_attack1",		&morcalavin_move_tracking_attack1 },
	{ "morcalavin_move_walk",					&morcalavin_move_walk },

	// m_mother_anim.c:
	{ "mother_move_pain",						&mother_move_pain },
	{ "mother_move_stand",						&mother_move_stand },

	// m_mssithra_anim.c:
	{ "mssithra_move_backpedal1",				&mssithra_move_backpedal1 },
	{ "mssithra_move_claw1",					&mssithra_move_claw1 },
	{ "mssithra_move_death1",					&mssithra_move_death1 },
	{ "mssithra_move_delay",					&mssithra_move_delay },
	{ "mssithra_move_fjump",					&mssithra_move_fjump },
	{ "mssithra_move_idle1",					&mssithra_move_idle1 },
	{ "mssithra_move_jump1",					&mssithra_move_jump1 },
	{ "mssithra_move_roar",						&mssithra_move_roar },
	{ "mssithra_move_run1",						&mssithra_move_run1 },
	{ "mssithra_move_shoot1_detrans",			&mssithra_move_shoot1_detrans },
	{ "mssithra_move_shoot1_loop",				&mssithra_move_shoot1_loop },
	{ "mssithra_move_shoot1_trans",				&mssithra_move_shoot1_trans },
	{ "mssithra_move_shoota1",					&mssithra_move_shoota1 },
	{ "mssithra_move_shootb1",					&mssithra_move_shootb1 },
	{ "mssithra_move_walk1",					&mssithra_move_walk1 },

	// m_ogle_anim.c:
	{ "ogle_c_move_action1",					&ogle_c_move_action1 },
	{ "ogle_c_move_action10",					&ogle_c_move_action10 },
	{ "ogle_c_move_action11",					&ogle_c_move_action11 },
	{ "ogle_c_move_action12",					&ogle_c_move_action12 },
	{ "ogle_c_move_action13",					&ogle_c_move_action13 },
	{ "ogle_c_move_action14",					&ogle_c_move_action14 },
	{ "ogle_c_move_action15",					&ogle_c_move_action15 },
	{ "ogle_c_move_action2",					&ogle_c_move_action2 },
	{ "ogle_c_move_action3",					&ogle_c_move_action3 },
	{ "ogle_c_move_action4",					&ogle_c_move_action4 },
	{ "ogle_c_move_action5",					&ogle_c_move_action5 },
	{ "ogle_c_move_action6",					&ogle_c_move_action6 },
	{ "ogle_c_move_action7",					&ogle_c_move_action7 },
	{ "ogle_c_move_action8",					&ogle_c_move_action8 },
	{ "ogle_c_move_action9",					&ogle_c_move_action9 },
	{ "ogle_c_move_attack1",					&ogle_c_move_attack1 },
	{ "ogle_c_move_attack2",					&ogle_c_move_attack2 },
	{ "ogle_c_move_attack3",					&ogle_c_move_attack3 },
	{ "ogle_c_move_death1",						&ogle_c_move_death1 },
	{ "ogle_c_move_death2",						&ogle_c_move_death2 },
	{ "ogle_c_move_idle1",						&ogle_c_move_idle1 },
	{ "ogle_c_move_idle2",						&ogle_c_move_idle2 },
	{ "ogle_c_move_idle3",						&ogle_c_move_idle3 },
	{ "ogle_c_move_idle4",						&ogle_c_move_idle4 },
	{ "ogle_c_move_idle5",						&ogle_c_move_idle5 },
	{ "ogle_c_move_idle6",						&ogle_c_move_idle6 },
	{ "ogle_c_move_pain1",						&ogle_c_move_pain1 },
	{ "ogle_c_move_pain2",						&ogle_c_move_pain2 },
	{ "ogle_c_move_pain3",						&ogle_c_move_pain3 },
	{ "ogle_c_move_trans1",						&ogle_c_move_trans1 },
	{ "ogle_c_move_trans2",						&ogle_c_move_trans2 },
	{ "ogle_c_move_trans3",						&ogle_c_move_trans3 },
	{ "ogle_c_move_trans4",						&ogle_c_move_trans4 },
	{ "ogle_c_move_trans5",						&ogle_c_move_trans5 },
	{ "ogle_c_move_trans6",						&ogle_c_move_trans6 },
	{ "ogle_c_move_walk1",						&ogle_c_move_walk1 },
	{ "ogle_c_move_walk2",						&ogle_c_move_walk2 },
	{ "ogle_c_move_walk3",						&ogle_c_move_walk3 },
	{ "ogle_c_move_walk4",						&ogle_c_move_walk4 },
	{ "ogle_move_attack1",						&ogle_move_attack1 },
	{ "ogle_move_attack2",						&ogle_move_attack2 },
	{ "ogle_move_attack3",						&ogle_move_attack3 },
	{ "ogle_move_celebrate1",					&ogle_move_celebrate1 },
	{ "ogle_move_celebrate2",					&ogle_move_celebrate2 },
	{ "ogle_move_celebrate3",					&ogle_move_celebrate3 },
	{ "ogle_move_celebrate3_trans",				&ogle_move_celebrate3_trans },
	{ "ogle_move_celebrate4",					&ogle_move_celebrate4 },
	{ "ogle_move_celebrate4_trans",				&ogle_move_celebrate4_trans },
	{ "ogle_move_celebrate5",					&ogle_move_celebrate5 },
	{ "ogle_move_celebrate5_trans",				&ogle_move_celebrate5_trans },
	{ "ogle_move_charge1",						&ogle_move_charge1 },
	{ "ogle_move_charge2",						&ogle_move_charge2 },
	{ "ogle_move_charge3",						&ogle_move_charge3 },
	{ "ogle_move_charge4",						&ogle_move_charge4 },
	{ "ogle_move_charge5",						&ogle_move_charge5 },
	{ "ogle_move_death1",						&ogle_move_death1 },
	{ "ogle_move_death2",						&ogle_move_death2 },
	{ "ogle_move_pain1",						&ogle_move_pain1 },
	{ "ogle_move_pain2",						&ogle_move_pain2 },
	{ "ogle_move_pain3",						&ogle_move_pain3 },
	{ "ogle_move_push1",						&ogle_move_push1 },
	{ "ogle_move_push2",						&ogle_move_push2 },
	{ "ogle_move_push3",						&ogle_move_push3 },
	{ "ogle_move_rest1",						&ogle_move_rest1 },
	{ "ogle_move_rest1_trans",					&ogle_move_rest1_trans },
	{ "ogle_move_rest1_wipe",					&ogle_move_rest1_wipe },
	{ "ogle_move_rest2_wipe",					&ogle_move_rest2_wipe },
	{ "ogle_move_rest3_wipe",					&ogle_move_rest3_wipe },
	{ "ogle_move_rest4",						&ogle_move_rest4 },
	{ "ogle_move_rest4_trans",					&ogle_move_rest4_trans },
	{ "ogle_move_rest4_trans2",					&ogle_move_rest4_trans2 },
	{ "ogle_move_stand1",						&ogle_move_stand1 },
	{ "ogle_move_walk1",						&ogle_move_walk1 },
	{ "ogle_move_work1",						&ogle_move_work1 },
	{ "ogle_move_work2",						&ogle_move_work2 },
	{ "ogle_move_work3",						&ogle_move_work3 },
	{ "ogle_move_work4",						&ogle_move_work4 },
	{ "ogle_move_work5",						&ogle_move_work5 },

	// m_plagueElf_anim.c:
	{ "plagueElf_crazy_A",						&plagueElf_crazy_A },
	{ "plagueElf_crazy_B",						&plagueElf_crazy_B },
	{ "plagueElf_cursing",						&plagueElf_cursing },
	{ "plagueElf_delay",						&plagueElf_delay },
	{ "plagueElf_fist1",						&plagueElf_fist1 },
	{ "plagueElf_lean1",						&plagueElf_lean1 },
	{ "plagueElf_move_c_attack1",				&plagueElf_move_c_attack1 },
	{ "plagueElf_move_c_attack2",				&plagueElf_move_c_attack2 },
	{ "plagueElf_move_c_attack3",				&plagueElf_move_c_attack3 },
	{ "plagueElf_move_c_attack4",				&plagueElf_move_c_attack4 },
	{ "plagueElf_move_c_death1",				&plagueElf_move_c_death1 },
	{ "plagueElf_move_c_death2",				&plagueElf_move_c_death2 },
	{ "plagueElf_move_c_death3",				&plagueElf_move_c_death3 },
	{ "plagueElf_move_c_death4",				&plagueElf_move_c_death4 },
	{ "plagueElf_move_c_idle1",					&plagueElf_move_c_idle1 },
	{ "plagueElf_move_c_idle2",					&plagueElf_move_c_idle2 },
	{ "plagueElf_move_c_idle3",					&plagueElf_move_c_idle3 },
	{ "plagueElf_move_c_pain1",					&plagueElf_move_c_pain1 },
	{ "plagueElf_move_c_run",					&plagueElf_move_c_run },
	{ "plagueElf_move_c_walk",					&plagueElf_move_c_walk },
	{ "plagueElf_move_c_walk2",					&plagueElf_move_c_walk2 },
	{ "plagueElf_move_death1",					&plagueElf_move_death1 },
	{ "plagueElf_move_death2",					&plagueElf_move_death2 },
	{ "plagueElf_move_death3",					&plagueElf_move_death3 },
	{ "plagueElf_move_death4",					&plagueElf_move_death4 },
	{ "plagueElf_move_fjump",					&plagueElf_move_fjump },
	{ "plagueElf_move_inair",					&plagueElf_move_inair },
	{ "plagueElf_move_kdeath_end",				&plagueElf_move_kdeath_end },
	{ "plagueElf_move_kdeath_go",				&plagueElf_move_kdeath_go },
	{ "plagueElf_move_kdeath_loop",				&plagueElf_move_kdeath_loop },
	{ "plagueElf_move_land",					&plagueElf_move_land },
	{ "plagueElf_move_melee1",					&plagueElf_move_melee1 },
	{ "plagueElf_move_melee2",					&plagueElf_move_melee2 },
	{ "plagueElf_move_missile",					&plagueElf_move_missile },
	{ "plagueElf_move_pain1",					&plagueElf_move_pain1 },
	{ "plagueElf_move_run1",					&plagueElf_move_run1 },
	{ "plagueElf_move_runatk1",					&plagueElf_move_runatk1 },
	{ "plagueElf_move_stand1",					&plagueElf_move_stand1 },
	{ "plagueElf_move_walk1",					&plagueElf_move_walk1 },
	{ "plagueElf_move_walk2",					&plagueElf_move_walk2 },
	{ "plagueElf_point",						&plagueElf_point },
	{ "plagueElf_scared",						&plagueElf_scared },
	{ "plagueElf_shake1",						&plagueElf_shake1 },

	// m_plagueSsithra_anim.c:
	{ "ssithra_move_backpedal1",				&ssithra_move_backpedal1 },
	{ "ssithra_move_bound1",					&ssithra_move_bound1 },
	{ "ssithra_move_dead_a",					&ssithra_move_dead_a },
	{ "ssithra_move_dead_b",					&ssithra_move_dead_b },
	{ "ssithra_move_dead_water",				&ssithra_move_dead_water },
	{ "ssithra_move_death_a1",					&ssithra_move_death_a1 },
	{ "ssithra_move_death_b1",					&ssithra_move_death_b1 },
	{ "ssithra_move_death_c",					&ssithra_move_death_c },
	{ "ssithra_move_delay",						&ssithra_move_delay },
	{ "ssithra_move_dive1",						&ssithra_move_dive1 },
	{ "ssithra_move_duck1",						&ssithra_move_duck1 },
	{ "ssithra_move_duckloop",					&ssithra_move_duckloop },
	{ "ssithra_move_duckshoot1",				&ssithra_move_duckshoot1 },
	{ "ssithra_move_faceandnamor",				&ssithra_move_faceandnamor },
	{ "ssithra_move_fjump",						&ssithra_move_fjump },
	{ "ssithra_move_gallop1",					&ssithra_move_gallop1 },
	{ "ssithra_move_headless",					&ssithra_move_headless },
	{ "ssithra_move_headlessloop",				&ssithra_move_headlessloop },
	{ "ssithra_move_idle1",						&ssithra_move_idle1 },
	{ "ssithra_move_idlebasic1",				&ssithra_move_idlebasic1 },
	{ "ssithra_move_idleright1",				&ssithra_move_idleright1 },
	{ "ssithra_move_lookleft",					&ssithra_move_lookleft },
	{ "ssithra_move_lookright",					&ssithra_move_lookright },
	{ "ssithra_move_lunge",						&ssithra_move_lunge },
	{ "ssithra_move_melee1",					&ssithra_move_melee1 },
	{ "ssithra_move_meleest",					&ssithra_move_meleest },
	{ "ssithra_move_namor1",					&ssithra_move_namor1 },
	{ "ssithra_move_pain_a1",					&ssithra_move_pain_a1 },
	{ "ssithra_move_run1",						&ssithra_move_run1 },
	{ "ssithra_move_shoot1",					&ssithra_move_shoot1 },
	{ "ssithra_move_sliced",					&ssithra_move_sliced },
	{ "ssithra_move_spinleft",					&ssithra_move_spinleft },
	{ "ssithra_move_spinleft_go",				&ssithra_move_spinleft_go },
	{ "ssithra_move_spinright",					&ssithra_move_spinright },
	{ "ssithra_move_spinright_go",				&ssithra_move_spinright_go },
	{ "ssithra_move_startle1",					&ssithra_move_startle1 },
	{ "ssithra_move_swimforward1",				&ssithra_move_swimforward1 },
	{ "ssithra_move_swimwander",				&ssithra_move_swimwander },
	{ "ssithra_move_transdown",					&ssithra_move_transdown },
	{ "ssithra_move_transup",					&ssithra_move_transup },
	{ "ssithra_move_unduck",					&ssithra_move_unduck },
	{ "ssithra_move_walk1",						&ssithra_move_walk1 },
	{ "ssithra_move_water_death1",				&ssithra_move_water_death1 },
	{ "ssithra_move_water_idle1",				&ssithra_move_water_idle1 },
	{ "ssithra_move_water_pain_a1",				&ssithra_move_water_pain_a1 },
	{ "ssithra_move_water_pain_b1",				&ssithra_move_water_pain_b1 },
	{ "ssithra_move_water_shoot1",				&ssithra_move_water_shoot1 },

	// m_priestess_anim.c:
	{ "priestess_move_attack1_end",				&priestess_move_attack1_end },
	{ "priestess_move_attack1_go",				&priestess_move_attack1_go },
	{ "priestess_move_attack1_loop",			&priestess_move_attack1_loop },
	{ "priestess_move_attack2",					&priestess_move_attack2 },
	{ "priestess_move_attack3_end",				&priestess_move_attack3_end },
	{ "priestess_move_attack3_go",				&priestess_move_attack3_go },
	{ "priestess_move_attack3_loop",			&priestess_move_attack3_loop },
	{ "priestess_move_backup",					&priestess_move_backup },
	{ "priestess_move_death",					&priestess_move_death },
	{ "priestess_move_dodge_left",				&priestess_move_dodge_left },
	{ "priestess_move_dodge_right",				&priestess_move_dodge_right },
	{ "priestess_move_idle",					&priestess_move_idle },
	{ "priestess_move_idle_pose",				&priestess_move_idle_pose },
	{ "priestess_move_jump",					&priestess_move_jump },
	{ "priestess_move_jump_attack",				&priestess_move_jump_attack },
	{ "priestess_move_jump_back",				&priestess_move_jump_back },
	{ "priestess_move_jump_forward",			&priestess_move_jump_forward },
	{ "priestess_move_jump_left",				&priestess_move_jump_left },
	{ "priestess_move_jump_pounce",				&priestess_move_jump_pounce },
	{ "priestess_move_jump_right",				&priestess_move_jump_right },
	{ "priestess_move_pain",					&priestess_move_pain },
	{ "priestess_move_pose_trans",				&priestess_move_pose_trans },
	{ "priestess_move_pounce_attack",			&priestess_move_pounce_attack },
	{ "priestess_move_shield_end",				&priestess_move_shield_end },
	{ "priestess_move_shield_go",				&priestess_move_shield_go },
	{ "priestess_move_stand1",					&priestess_move_stand1 },
	{ "priestess_move_walk",					&priestess_move_walk },

	// m_rat_anim.c:
	{ "rat_move_death1",						&rat_move_death1 },
	{ "rat_move_death2",						&rat_move_death2 },
	{ "rat_move_eat1",							&rat_move_eat1 },
	{ "rat_move_eat2",							&rat_move_eat2 },
	{ "rat_move_eat3",							&rat_move_eat3 },
	{ "rat_move_melee1",						&rat_move_melee1 },
	{ "rat_move_melee2",						&rat_move_melee2 },
	{ "rat_move_melee3",						&rat_move_melee3 },
	{ "rat_move_pain1",							&rat_move_pain1 },
	{ "rat_move_run1",							&rat_move_run1 },
	{ "rat_move_run2",							&rat_move_run2 },
	{ "rat_move_run3",							&rat_move_run3 },
	{ "rat_move_stand1",						&rat_move_stand1 },
	{ "rat_move_stand2",						&rat_move_stand2 },
	{ "rat_move_stand3",						&rat_move_stand3 },
	{ "rat_move_stand4",						&rat_move_stand4 },
	{ "rat_move_stand5",						&rat_move_stand5 },
	{ "rat_move_stand6",						&rat_move_stand6 },
	{ "rat_move_stand7",						&rat_move_stand7 },
	{ "rat_move_stand8",						&rat_move_stand8 },
	{ "rat_move_walk1",							&rat_move_walk1 },
	{ "rat_move_watch1",						&rat_move_watch1 },
	{ "rat_move_watch2",						&rat_move_watch2 },

	// m_seraph_anim.c:
	{ "seraph_move_backup",						&seraph_move_backup },
	{ "seraph_move_backup2",					&seraph_move_backup2 },
	{ "seraph_move_death1",						&seraph_move_death1 },
	{ "seraph_move_death2_end",					&seraph_move_death2_end },
	{ "seraph_move_death2_go",					&seraph_move_death2_go },
	{ "seraph_move_death2_loop",				&seraph_move_death2_loop },
	{ "seraph_move_fjump",						&seraph_move_fjump },
	{ "seraph_move_get2work",					&seraph_move_get2work },
	{ "seraph_move_get2work2",					&seraph_move_get2work2 },
	{ "seraph_move_pain",						&seraph_move_pain },
	{ "seraph_move_point1",						&seraph_move_point1 },
	{ "seraph_move_ready2idle",					&seraph_move_ready2idle },
	{ "seraph_move_run1",						&seraph_move_run1 },
	{ "seraph_move_run1_whip",					&seraph_move_run1_whip },
	{ "seraph_move_stand1",						&seraph_move_stand1 },
	{ "seraph_move_stand1_l",					&seraph_move_stand1_l },
	{ "seraph_move_stand1_r",					&seraph_move_stand1_r },
	{ "seraph_move_stand1_tl",					&seraph_move_stand1_tl },
	{ "seraph_move_stand1_tlc",					&seraph_move_stand1_tlc },
	{ "seraph_move_stand1_tr",					&seraph_move_stand1_tr },
	{ "seraph_move_stand1_trc",					&seraph_move_stand1_trc },
	{ "seraph_move_startle",					&seraph_move_startle },
	{ "seraph_move_swipe",						&seraph_move_swipe },
	{ "seraph_move_walk1",						&seraph_move_walk1 },
	{ "seraph_move_walk2",						&seraph_move_walk2 },
	{ "seraph_move_whip1",						&seraph_move_whip1 },
	{ "seraph_move_whip1_end",					&seraph_move_whip1_end },
	{ "seraph_move_whip1_loop",					&seraph_move_whip1_loop },

	// m_seraph_guard_anim.c:
	{ "seraph_guard_move_backup",				&seraph_guard_move_backup },
	{ "seraph_guard_move_death1",				&seraph_guard_move_death1 },
	{ "seraph_guard_move_death2_end",			&seraph_guard_move_death2_end },
	{ "seraph_guard_move_death2_go",			&seraph_guard_move_death2_go },
	{ "seraph_guard_move_death2_loop",			&seraph_guard_move_death2_loop },
	{ "seraph_guard_move_delay",				&seraph_guard_move_delay },
	{ "seraph_guard_move_fjump",				&seraph_guard_move_fjump },
	{ "seraph_guard_move_melee",				&seraph_guard_move_melee },
	{ "seraph_guard_move_melee2",				&seraph_guard_move_melee2 },
	{ "seraph_guard_move_melee3",				&seraph_guard_move_melee3 },
	{ "seraph_guard_move_missile",				&seraph_guard_move_missile },
	{ "seraph_guard_move_pain",					&seraph_guard_move_pain },
	{ "seraph_guard_move_run",					&seraph_guard_move_run },
	{ "seraph_guard_move_runmelee",				&seraph_guard_move_runmelee },
	{ "seraph_guard_move_stand",				&seraph_guard_move_stand },
	{ "seraph_guard_move_walk",					&seraph_guard_move_walk },

	// m_spreader_anim.c:
	{ "spreader_move_attack1",					&spreader_move_attack1 },
	{ "spreader_move_attack2",					&spreader_move_attack2 },
	{ "spreader_move_backattack1",				&spreader_move_backattack1 },
	{ "spreader_move_backup1",					&spreader_move_backup1 },
	{ "spreader_move_dead",						&spreader_move_dead },
	{ "spreader_move_death1_end",				&spreader_move_death1_end },
	{ "spreader_move_death1_go",				&spreader_move_death1_go },
	{ "spreader_move_death1_loop",				&spreader_move_death1_loop },
	{ "spreader_move_death2",					&spreader_move_death2 },
	{ "spreader_move_delay",					&spreader_move_delay },
	{ "spreader_move_dkatck1",					&spreader_move_dkatck1 },
	{ "spreader_move_duck1",					&spreader_move_duck1 },
	{ "spreader_move_duckdown",					&spreader_move_duckdown },
	{ "spreader_move_duckstill",				&spreader_move_duckstill },
	{ "spreader_move_duckup",					&spreader_move_duckup },
	{ "spreader_move_fdie",						&spreader_move_fdie },
	{ "spreader_move_fjump",					&spreader_move_fjump },
	{ "spreader_move_fly",						&spreader_move_fly },
	{ "spreader_move_flyloop",					&spreader_move_flyloop },
	{ "spreader_move_idle1",					&spreader_move_idle1 },
	{ "spreader_move_inair",					&spreader_move_inair },
	{ "spreader_move_land",						&spreader_move_land },
	{ "spreader_move_pain1",					&spreader_move_pain1 },
	{ "spreader_move_pvtlt1",					&spreader_move_pvtlt1 },
	{ "spreader_move_pvtrt1",					&spreader_move_pvtrt1 },
	{ "spreader_move_rnatck1",					&spreader_move_rnatck1 },
	{ "spreader_move_run1",						&spreader_move_run1 },
	{ "spreader_move_walk1",					&spreader_move_walk1 },
	{ "spreader_move_walk2",					&spreader_move_walk2 },

	// m_tcheckrik_anim.c:
	{ "insect_delay",							&insect_delay },
	{ "insect_move_back",						&insect_move_back },
	{ "insect_move_c_action1",					&insect_move_c_action1 },
	{ "insect_move_c_action2",					&insect_move_c_action2 },
	{ "insect_move_c_action3",					&insect_move_c_action3 },
	{ "insect_move_c_action4",					&insect_move_c_action4 },
	{ "insect_move_c_attack1",					&insect_move_c_attack1 },
	{ "insect_move_c_attack2",					&insect_move_c_attack2 },
	{ "insect_move_c_attack3",					&insect_move_c_attack3 },
	{ "insect_move_c_backpedal",				&insect_move_c_backpedal },
	{ "insect_move_c_death1",					&insect_move_c_death1 },
	{ "insect_move_c_idle1",					&insect_move_c_idle1 },
	{ "insect_move_c_idle2",					&insect_move_c_idle2 },
	{ "insect_move_c_idle3",					&insect_move_c_idle3 },
	{ "insect_move_c_pain1",					&insect_move_c_pain1 },
	{ "insect_move_c_run",						&insect_move_c_run },
	{ "insect_move_c_walk",						&insect_move_c_walk },
	{ "insect_move_deathfr",					&insect_move_deathfr },
	{ "insect_move_finair",						&insect_move_finair },
	{ "insect_move_fjump",						&insect_move_fjump },
	{ "insect_move_forcedjump",					&insect_move_forcedjump },
	{ "insect_move_idle",						&insect_move_idle },
	{ "insect_move_inair",						&insect_move_inair },
	{ "insect_move_knock1_end",					&insect_move_knock1_end },
	{ "insect_move_knock1_go",					&insect_move_knock1_go },
	{ "insect_move_knock1_loop",				&insect_move_knock1_loop },
	{ "insect_move_land",						&insect_move_land },
	{ "insect_move_paina",						&insect_move_paina },
	{ "insect_move_painc",						&insect_move_painc },
	{ "insect_move_run",						&insect_move_run },
	{ "insect_move_spear",						&insect_move_spear },
	{ "insect_move_spell",						&insect_move_spell },
	{ "insect_move_spell2",						&insect_move_spell2 },
	{ "insect_move_sword",						&insect_move_sword },
	{ "insect_move_twitch",						&insect_move_twitch },
	{ "insect_move_walk",						&insect_move_walk },

	// Terminator field.
	{ NULL, NULL }
};

#pragma endregion