---
name: Create release for new tags

on:
  push:
    tags:
      - 'v*'
      - 'r*'
      - 'R*'

jobs:
  create-release:
    name: Create release if needed
    runs-on: ubuntu-latest
    steps:
      - name: Create release for new release tags
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
